# quotes_mega.py – Mega Extended Quotes (TR & EN)
# Generated from your current quotes.py and expanded with many extra quotes.

QUOTES_TR = {'Motivasyon': ['Zorluklar, güçlü insanları yaratır.',
                'Başlamak için mükemmel olmak zorunda değilsin.',
                'Devam eden kazanır.',
                'Bugün attığın küçük bir adım, yarın büyük bir değişim yaratır.',
                'Kendine inan; gerisi zaten gelir.',
                'Başlamaktan daha zor olan tek şey, vazgeçmemektir.',
                'Her gün biraz daha iyi ol.',
                'Hayallerine giden yol cesaret ister.',
                'Başarıya giden yol, konfor alanının dışından geçer.',
                'Hedefine odaklan, gürültüyü sustur.',
                'Güçlü olmanın en iyi yolu, zor zamanlardan geçmektir.',
                'Yapabileceğini düşünüyorsan, zaten yarı yolun dasın.',
                'Bugün yapabildiğini yap; yarın daha fazlasını yaparsın.',
                'Ne kadar yavaş gittiğin önemli değil, durmadığın sürece yol alırsın. — Konfüçyüs',
                'Hayatta en büyük zafer, hiç düşmemek değil; her düştüğünde yeniden ayağa '
                'kalkmaktır. — Nelson Mandela',
                'Yapabileceğine inan; gerisi zaten kendiliğinden gelecektir. — Theodore Roosevelt',
                'Güçlü olan, zayıf anında pes etmeyendir. — Vince Lombardi',
                'Bugünün şüpheleri, yarının gerçeklerini sınırlar. — Franklin D. Roosevelt',
                'İlk adım, en büyük adımdır. — Anonim',
                'Bugün vazgeçmezsen, yarın gurur duyarsın. — Anonim',
                'Cesaret, korkuya rağmen devam etmektir. — Anonim',
                'Başlamak, yarı yarıya bitirmektir. — Anonim',
                'Yol uzun diye dönme; her adım seni yaklaştırır. — Anonim',
                'Bin millik yolculuk tek bir adımla başlar. — Lao Tzu',
                'Yaşamak cesaret işidir. — Cemal Süreya',
                'Yıldızlara ulaşmak için gözlerini yukarı kaldır. — Anonim',
                'Hayal ettiğin şey için çalış; şikayet için değil. — Anonim',
                'İmkânsız, sadece bir fikirden ibarettir. — Anonim'],
 'Başarı': ['Başarı tesadüf değildir; emek ister.',
            'Hazırlık şansı yakalayınca başarı ortaya çıkar.',
            'Ne kadar çok çalışırsan o kadar şanslı olursun.',
            'Başarı, küçük zaferlerin toplamıdır.',
            'Her başarının arkasında görünmeyen bir çaba vardır.',
            'Doğru zamanda doğru yerde olmak değil; doğru kişi olmak önemlidir.',
            'Kazanmak istiyorsan önce inanmalısın.',
            'Başarı bazen sadece bir adım daha devam etmektir.',
            'Fırsatlar hazırlanmış zihinlere gelir.',
            'Pes etmeyenler en sonunda kazanır.',
            'Disiplin olmadan başarı olmaz.',
            'Yavaş ilerlemek durmaktan iyidir.',
            'Başarı, hazırlık ile fırsatın buluştuğu yerdir. — Seneca',
            'Kazananlar asla vazgeçmez; vazgeçenler asla kazanamaz. — Vince Lombardi',
            'Başarı, her gün tekrarlanan küçük çabaların toplamıdır. — Robert Collier',
            'Fırsatlar kendiliğinden olmaz; sen yaratırsın. — Chris Grosser',
            'Başarı, çoğunlukla başkalarının pes ettiği noktadan sonra gelir. — William Feather',
            'Başarı, düşe kalka yürümeye devam etmektir. — Anonim',
            'İstikrar, gizli hızdır. — Anonim',
            'Başarı, doğru alışkanlıkların yan ürünüdür. — Anonim',
            'İyi şeyler zaman alır; harika şeyler daha çok. — Anonim',
            'Planla, uygula, geliştir. — Anonim',
            'Başarı, fırsat geldiğinde hazır olmaktır. — Benjamin Disraeli',
            'Başarısızlık, yeniden başlama fırsatıdır. — Henry Ford',
            'Başarı, kendini aşma sanatıdır. — Anonim',
            'En büyük başarı, vazgeçmemeyi seçmektir. — Anonim',
            'Yapabileceğini kanıtlamak için tek kişiye ihtiyacın var: kendin. — Anonim'],
 'Hayat': ['Hayat, cesur olana fırsatlar sunar.',
           'Dün geçti, yarın bilinmez; bugün yaşanır.',
           'Mutluluk, paylaştıkça çoğalır.',
           'Hayat kısa, onu anlamlı yapan sensin.',
           'Her gün yeni bir başlangıçtır.',
           'Zaman geri gelmez; iyi kullan.',
           'Hayatın ritmini sen belirlersin.',
           'Düşüncelerin hayatını şekillendirir.',
           'Bazen en büyük yolculuk, kendine yaptığındır.',
           'Hayat, seçimlerin toplamıdır.',
           'Sadelik çoğu zaman mutluluğun anahtarıdır.',
           'Bugünü güzel yaşa; yarın belirsizdir.',
           'Hayat, biz başka planlar yaparken başımıza gelenlerdir. — John Lennon',
           'Dünyada görmek istediğin değişim ol. — Mahatma Gandhi',
           'İnsanların çoğu, mutlu olmaya karar verdikleri ölçüde mutludur. — Abraham Lincoln',
           'Yaşam cesurları ödüllendirir. — Virgil',
           'Önemli olan, yıllara ne kadar hayat sığdırdığın. — Abraham Lincoln',
           'Hayat, nefes almak değil; nefes kesen anlar biriktirmektir. — Anonim',
           'Basit yaşa, derin hisset. — Anonim',
           'Her şey geçer; bu da geçer. — Anonim',
           'Bugün, kalan hayatının ilk günü. — Anonim',
           'Hayat, küçük seçimlerin büyük toplamıdır. — Anonim',
           'Mutluluk, yolun üzerindedir; varışta değil. — Buddha',
           'Hayatını değiştirmek istiyorsan alışkanlıklarını değiştir. — Anonim',
           'İyi bir hayat, iyi niyetle başlar. — Anonim',
           'Yaşadıkların değil, onlara verdiğin anlam seni şekillendirir. — Anonim',
           'Her sabah yeniden doğarsın; bugün ne yapacağın önemlidir. — Buddha'],
 'Kendine iyi bak': ['Kendine iyi bakmak, hayata iyi bakmaktır.',
                     'Önce sen iyi ol ki dünya sana iyi gelsin.',
                     'Bedenine ve zihnine iyi davran.',
                     'Kendini ihmal etmek, geleceğini ihmal etmektir.',
                     'Dinlenmek de üretmektir.',
                     'İyileşmek zaman ister; kendine sabırlı davran.',
                     'Sen değerlisin, kendine öyle davran.',
                     'Ruhunu beslemeyi unutma.',
                     'Kendine şefkat göster.',
                     'Duygularını bastırma; anlamaya çalış.',
                     'Zihnini temizle, enerjin tazelensin.',
                     'Kendine ayırdığın zaman asla boşa gitmez.',
                     'Kendine karşı nazik ol; ruhun da bunu duyar. — Buddha',
                     'Bedenin, ruhunun evindir; ona iyi bak. — Seneca',
                     'Zihninize yatırım yapmak, yapacağınız en iyi yatırımdır. — Benjamin Franklin',
                     'Kendini sevmek, ömür boyu sürecek bir aşkın başlangıcıdır. — Oscar Wilde',
                     'İç huzur, hayattaki en büyük servettir. — Dalai Lama',
                     'Hayır demek, kendine evet demektir. — Anonim',
                     'Dinlenmek tembellik değil, bakımın bir parçasıdır. — Anonim',
                     'Kendine iyi davran; seninle 24 saat birlikte olan sensin. — Anonim',
                     'Yeterince iyi olmak da bir başarıdır. — Anonim',
                     'Zihnin yorulduysa, bedenin dinlenmesi yetmez. — Anonim',
                     'Kendini kıyaslama; kendi yolunda yürü. — Anonim',
                     'Nefes al, omuzlarını indir, devam et. — Anonim',
                     'İyileşmek, aceleye gelmez. — Anonim',
                     'Küçük rutinler, büyük huzur getirir. — Anonim',
                     'Kendine şefkat, gücün en sessiz halidir. — Anonim'],
 'Spor': ['Kelebek gibi uçar, arı gibi sokarım. — Muhammed Ali',
          'Zorluklar şampiyonları belirler.',
          'Ter, başarıya açılan kapının anahtarıdır.',
          'Zafer, hazırlananlarındır. — Herodot',
          'Her tekrar seni güçlendirir.',
          'Disiplin, sporcunun gerçek gücüdür.',
          'Sınırlarını zorla; potansiyelini keşfet.',
          'Bugünün acısı yarının gücüdür.',
          'Spor, bedenin ve zihnin uyumudur.',
          'Pes etme, bir tekrar daha yap.',
          'Koşarken düşünceler değil, adımlar önemlidir.',
          'Güçlü olmak bir tercih meselesidir.',
          'Antrenman yalan söylemez.',
          'Kazanmak için önce kaybetmeyi öğrenmelisin. — Serena Williams',
          'Başarısızlığı kabul edebilirim ama denememeyi asla. — Michael Jordan',
          'Zorlu anlar güçlü insanlar yaratır. — Kobe Bryant',
          'Hiçbir şey, çalışanı durduramaz. — Eliud Kipchoge',
          'Acı geçicidir, pes etmek kalıcıdır. — Lance Armstrong',
          'Bugün antrenman, yarın özgüven. — Anonim',
          'Koşu biter; karakter kalır. — Anonim',
          'Her kilometre, zihnini de güçlendirir. — Anonim',
          'Şampiyonluk, sıradan günlerde kazanılır. — Anonim',
          'Isınma bir bahane değil; bir disiplindir. — Anonim',
          'Acıyı sevme; onunla barış. — Anonim',
          'Yorulduğunda durma; yavaşla. — Anonim',
          'Güç, tekrarlarla inşa edilir. — Anonim',
          'En iyi antrenman, yaptığındır. — Anonim',
          'Bugün ter, yarın gurur. — Anonim'],
 'Disiplin': ['Disiplin, başarının gizli anahtarıdır.',
              'Küçük disiplinler büyük zaferler getirir.',
              'İrade varsa yol vardır.',
              'Disiplin, özgürlüğün başlangıcıdır.',
              'Her gün tekrar eden küçük alışkanlıklar seni değiştirir.',
              'Motivasyon gelir gider; disiplin kalır.',
              'Kendini yönetebilmek en büyük başarıdır.',
              'İstikrarlı olan her zaman kazanır.',
              'Zor olanı yapmak karakteri inşa eder.',
              'Disiplin, gelecekteki senin için bugünkü fedakarlıktır.',
              'Ne yapman gerektiğini bilmek değil, yapmak önemlidir.',
              'Disiplinli olan yorulmaz; güçlenir.',
              'Disiplin, hedeflerle başarı arasındaki köprüdür. — Jim Rohn',
              'Özgürlük, disiplinle başlar. — Jocko Willink',
              'Biz, tekrarladığımız şeyiz; mükemmellik bir eylem değil, alışkanlıktır. — '
              'Aristoteles',
              'İrade, çalıştırıldıkça güçlenen bir kas gibidir. — Buddha',
              'Disiplin olmadan hiçbir başarı sürdürülebilir değildir. — John C. Maxwell',
              'Rutin kur, özgür ol. — Anonim',
              'Az ama her gün. — Anonim',
              'Disiplin, duyguların değil kararların eseridir. — Anonim',
              'İstek geçer; alışkanlık kalır. — Anonim',
              'Zor olanı seçmek, kolaylaşır. — Anonim',
              'Kendine söz ver; tut. — Anonim',
              'İstikrarlı ol; mucizeyi bekleme. — Anonim',
              'Bugün yaptıkların, yarınını yazar. — Anonim',
              'Disiplin, sessiz bir ‘evet’tir. — Anonim',
              'Küçük kurallar, büyük sonuçlar doğurur. — Anonim'],
 'Dostluk': ['Gerçek dostluk mesafe tanımaz.',
             'Dostluk iki beden içinde yaşayan tek ruhtur.',
             'Yanında yürüyen bir dost, yoldaki yükü hafifletir.',
             'Dost, zor günde belli olur.',
             'Gerçek arkadaşlık zamanla değil, samimiyetle ölçülür.',
             'Bir dost bir dünyadır.',
             'Dostluğun değeri paha biçilemez.',
             'Güven, dostluğun temelidir.',
             'İyi arkadaş, hayatı güzelleştirir.',
             'Birlikte gülmek en güzel bağdır.',
             'Dost, kalbinin aynasıdır.',
             'Yanında huzur bulduğun kişi dostundur.',
             'Dost, bütünün diğer yarısıdır. — Platon',
             'Gerçek dostluk, iki beden içinde yaşayan tek ruhtur. — Aristoteles',
             'Bir dost edinmek istiyorsan, bir dost ol. — Ralph Waldo Emerson',
             'Dostluk, mutluluğu artırır, acıyı azaltır. — Thomas Aquinas',
             'Gerçek dostluk, iki kişi arasındaki sessizliği bile anlamlı kılar. — David Tyson',
             'Dost, omzuna yük değil; omuz verir. — Anonim',
             'İyi dost, iyi aynadır. — Anonim',
             'Samimiyet, dostluğun dili. — Anonim',
             'Kalpten gelen, kalbe gider. — Anonim',
             'Dostluk, paylaşınca çoğalan tek şeydir. — Anonim',
             'Gerçek dost, başarıda değil; yorgunlukta yanında olandır. — Anonim',
             'Bir mesaj bazen ‘buradayım’ demektir. — Anonim',
             'Dostluk, küçük inceliklerde saklıdır. — Anonim',
             'Güven varsa mesafe sorun olmaz. — Anonim',
             'İyi arkadaşlık, iyi niyetin uzun halidir. — Anonim'],
 'Dayanıklılık': ['Vazgeçmeyen kazanır.',
                  'Her yara seni daha güçlü yapar.',
                  'Düşmek kaderindir, kalkmak tercihindir.',
                  'Zorluklar karakteri şekillendirir.',
                  'Her karanlık gecenin bir sabahı vardır.',
                  'Sabrın sonu daima güçtür.',
                  'Kırılmadan güçlenemezsin.',
                  'En zor anlarda bile ilerle.',
                  'Yıkılmadığın sürece yenilmedin.',
                  'Güçlü insanlar, savaşarak güçlenenlerdir.',
                  'Fırtına geçer, gökyüzü açılır.',
                  'Her nefes bir umuttur.',
                  'Beni öldürmeyen şey beni güçlendirir. — Friedrich Nietzsche',
                  'Karanlığın en yoğun olduğu an, şafak sökmeden hemen öncedir. — Thomas Fuller',
                  'Her zorluk, içinde bir fırsat taşır. — Albert Einstein',
                  'Umudu olan için hiçbir yol kapanmaz. — Desmond Tutu',
                  'Dayanıklılık, pes etmeyenlerin sessiz zaferidir. — Unknown',
                  'Fırtınalar geçer; sen kalırsın. — Anonim',
                  'Bugün zor, yarın güçlü. — Anonim',
                  'Yaraların, haritan olur. — Anonim',
                  'Yük ağırsa, güçleniyorsun demektir. — Anonim',
                  'Sabır, sessiz cesarettir. — Anonim',
                  'Kırılınca değil, vazgeçince biter. — Anonim',
                  'Düşünce değil, kalkışın önemli. — Anonim',
                  'Yeniden başlamak da bir güçtür. — Anonim',
                  'Her gün biraz daha dayanıklı ol. — Anonim',
                  'Direnç, tekrar tekrar denemektir. — Anonim'],
 'Yaratıcılık': ['Yaratıcılık zekânın eğlenmesidir.',
                 'Fikirler özgür bırakıldığında değer kazanır.',
                 'Hayal gücü her şeydir.',
                 'Her büyük eser bir fikirle başlar.',
                 'Merak, yaratıcılığın yakıtıdır.',
                 'Hayal kur; sınırlar ötesi seni bekler.',
                 'Yaratıcılık risk alınca ortaya çıkar.',
                 'Renklerin dili vardır; seninle konuşur.',
                 'Farklı düşünmek cesaret ister.',
                 'İlham her yerde; yeter ki bakmayı bil.',
                 'Basitlik en yaratıcı çözümdür.',
                 'Her yanlış deneme yeni bir keşiftir.',
                 'Hayal gücü bilgiden daha önemlidir. — Albert Einstein',
                 'Yaratıcılık bulaşıcıdır, yay. — Albert Einstein',
                 'Sanat, görünmeyeni görünür kılar. — Paul Klee',
                 'Yaratıcılık cesaret ister. — Henri Matisse',
                 'Fikirler, paylaşıldıkça büyür. — George Bernard Shaw',
                 'Yeni fikir, yeni yol demektir. — Anonim',
                 'Merak et; öğren; üret. — Anonim',
                 'Fikirler, cesaretle şekillenir. — Anonim',
                 'Yaratıcılık, ‘ya şöyle olsaydı?’ sorusudur. — Anonim',
                 'İlham bekleme; üretince gelir. — Anonim',
                 'Çizgiyi boz; yolu bul. — Anonim',
                 'Basit düşün, farklı yap. — Anonim',
                 'Yap ve geliştir; mükemmeli bekleme. — Anonim',
                 'Hata, denemenin imzasıdır. — Anonim',
                 'Hayal kurmak, tasarlamanın başlangıcıdır. — Anonim'],
 'İş & Kariyer': ['Küçük adımlar büyük kariyerler yaratır.',
                  'İşini sev, başarı seni takip eder.',
                  'Hazırlık, fırsatla buluştuğunda başarı doğar.',
                  'Kariyer bir yolculuktur; acele etme, ilerle.',
                  'Bilgi, kariyerin en güçlü silahıdır.',
                  'Hedefi olan yolunu bulur.',
                  'Çalışmak, başarıya yapılmış bir yatırımdır.',
                  'Üretkenlik alışkanlıktan doğar.',
                  'Doğru ekip, büyük fark yaratır.',
                  'Kendine yatırım en değerli yatırımdır.',
                  'Fırsatlar çalışana gelir.',
                  'Ne kadar öğrenirsen o kadar büyürsün.',
                  'Geleceği tahmin etmenin en iyi yolu onu yaratmaktır. — Peter Drucker',
                  'Mükemmellik bir eylem değil, alışkanlıktır. — Aristoteles',
                  'Harika işler başarmanın tek yolu, yaptığın işi sevmektir. — Steve Jobs',
                  'Her uzman bir zamanlar acemiydi. — Helen Hayes',
                  'Karşılığını almak istiyorsan önce değer üret. — Zig Ziglar',
                  'İtibar, en uzun vadeli yatırımdır. — Anonim',
                  'Sonuç değil süreç yönet. — Anonim',
                  'İyi iş, iyi alışkanlıktan çıkar. — Anonim',
                  'Bugün öğrendiğin, yarın maaşına dönüşür. — Anonim',
                  'İyi ekip, iyi liderlikle büyür. — Anonim',
                  'Profesyonellik, sözünde durmaktır. — Anonim',
                  'Az konuş, çok teslim et. — Anonim',
                  'Değer üret; görünür olursun. — Anonim',
                  'Sabır + emek = kariyer. — Anonim',
                  'Kariyer, bir gecede değil; her gün inşa edilir. — Anonim'],
 'Şükran': ['Şükür, sahip olduklarını çoğaltır.',
            'Minnettarlık huzurun kapısıdır.',
            'Teşekkür etmek ruhu hafifletir.',
            'Bugün için şükret; yarın için umut et.',
            'Şükreden insan, huzuru bulur.',
            'Küçük şeylere minnet etmek büyüklüğü getirir.',
            'Hayat güzeldir; fark edene.',
            'Şükür kalbi yumuşatır.',
            'Daha az şikayet, daha çok şükür.',
            'Sahip olduklarını fark et; her şey değişir.',
            'Mutluluk şükürle başlar.',
            'Teşekkür, en sade mutluluktur.',
            'Minnettarlık, erdemlerin en büyüğüdür. — Cicero',
            'Şükran, mutluluğun temelidir. — B. K. S. Iyengar',
            'Ne kadar şükredersen, şükredecek o kadar çok şey bulursun. — Oprah Winfrey',
            'Teşekkür etmek, ruhun en zarif sanatıdır. — Voltaire',
            'Mutlu insanların şükrettiği değil, şükredenlerin mutlu olduğu söylenir. — Unknown',
            'Şükür, yüreği genişletir. — Anonim',
            'Bugünün küçük sevinçlerini fark et. — Anonim',
            'Teşekkür, görünmeyeni görünür kılar. — Anonim',
            'Azla mutlu olabilen, çokla taşar. — Anonim',
            'Şükür, huzurun en kısa yoludur. — Anonim',
            'Her gün bir şeye teşekkür et. — Anonim',
            'İyiliği gör; çoğalır. — Anonim',
            'Elindekini sev; büyür. — Anonim',
            'Şükür, kalbin nefesidir. — Anonim',
            'Paylaşınca bereket artar. — Anonim']}


QUOTES_EN = {'Motivation': ['Difficult roads often lead to beautiful destinations.',
                'Start where you are, use what you have, do what you can.',
                "Keep going, you're getting stronger.",
                'Small steps today create big results tomorrow.',
                "Believe you can and you're halfway there.",
                'Growth begins at the end of your comfort zone.',
                'Your only limit is your mind.',
                'Push yourself; no one will do it for you.',
                'Great things take time—stay patient.',
                'You become what you repeatedly do.',
                "Stay committed, even when it's hard.",
                'Today is a perfect day to try.',
                'The only limit to our realization of tomorrow is our doubts of today. — F. D. '
                'Roosevelt',
                'Act as if what you do makes a difference. It does. — William James',
                'It always seems impossible until it’s done. — Nelson Mandela',
                'Whether you think you can or you think you can’t, you’re right. — Henry Ford',
                'You miss 100% of the shots you don’t take. — Wayne Gretzky',
                'One step can change everything. — Unknown',
                'Don’t wait for motivation; build momentum. — Unknown',
                'Progress, not perfection. — Unknown',
                'Your future self is watching. — Unknown',
                'Do it scared. — Unknown',
                'A journey of a thousand miles begins with a single step. — Lao Tzu',
                'Believe you deserve it and the universe will serve it. — Unknown',
                'Make it happen. Shock everyone. — Unknown',
                'If it matters to you, you’ll find a way. — Unknown',
                'Start now. Start messy. — Unknown'],
 'Success': ['Success is not final; failure is not fatal.',
             'Success is the sum of small efforts repeated daily.',
             'Dream big. Work hard. Stay focused.',
             'Success starts with self-belief.',
             'Winners are not people who never fail but people who never quit.',
             'Great achievements require dedication.',
             'Preparation turns opportunities into success.',
             'Your habits shape your success.',
             'Do what others won’t, achieve what others can’t.',
             'Every accomplishment begins with the decision to try.',
             'Stay hungry, stay humble.',
             'The harder you work, the greater the reward.',
             'Opportunities don’t happen. You create them. — Chris Grosser',
             'Success usually comes to those who are too busy to be looking for it. — H. D. '
             'Thoreau',
             'The way to get started is to quit talking and begin doing. — Walt Disney',
             'Success is walking from failure to failure with no loss of enthusiasm. — Winston '
             'Churchill',
             'If you can dream it, you can do it. — Walt Disney',
             'Success is rented, and rent is due every day. — Unknown',
             'Consistency beats talent when talent isn’t consistent. — Unknown',
             'Small wins add up. — Unknown',
             'Success is built on habits, not hype. — Unknown',
             'Focus on systems, not just goals. — Unknown',
             'Failure is simply the opportunity to begin again. — Henry Ford',
             'Success is the progressive realization of a worthy goal. — Earl Nightingale',
             'Luck is what happens when preparation meets opportunity. — Seneca',
             'Discipline is the foundation of success. — Unknown',
             'Dreams don’t work unless you do. — John C. Maxwell'],
 'Life': ['Life begins at the end of your comfort zone.',
          'Every moment is a fresh beginning.',
          'Happiness is found in the little things.',
          'Life is what you make it.',
          "Enjoy the present; it's all you truly have.",
          'Your thoughts shape your reality.',
          'Let go of what you can’t control.',
          'Choose joy every day.',
          'Life becomes easier when you stop comparing.',
          'What you focus on grows.',
          'Slow down; life is not a race.',
          'Be present, be grateful.',
          'Life is what happens while you are busy making other plans. — John Lennon',
          'Be the change that you wish to see in the world. — Mahatma Gandhi',
          'In the end, it’s not the years in your life that count. It’s the life in your years. — '
          'A. Lincoln',
          'Life rewards the brave. — Virgil',
          'The purpose of our lives is to be happy. — Dalai Lama',
          'This too shall pass. — Persian proverb',
          'Life is a collection of moments; make them count. — Unknown',
          'Wherever you go, go with all your heart. — Confucius',
          'Life is really simple, but we insist on making it complicated. — Confucius',
          'Be where your feet are. — Unknown',
          'Life is 10% what happens to you and 90% how you react. — Charles R. Swindoll',
          'Let your life be your message. — Mahatma Gandhi',
          'Live less out of habit and more out of intent. — Unknown',
          'Choose kindness; it always fits. — Unknown',
          'Everything has beauty, but not everyone sees it. — Confucius'],
 'Self-care': ['Take care of yourself first.',
               'Self-care is how you take your power back.',
               'Rest is part of the process.',
               'You deserve the same love you give others.',
               'Pausing is not quitting.',
               'Your well-being matters.',
               'Protect your energy.',
               'Healing takes time—be gentle with yourself.',
               "Breathe; you're doing your best.",
               'Prioritize your peace.',
               'Self-care is a daily practice.',
               "It's okay to take a break.",
               'To love oneself is the beginning of a lifelong romance. — Oscar Wilde',
               'The greatest wealth is health. — Virgil',
               'Almost everything will work again if you unplug it for a few minutes, including '
               'you. — Anne Lamott',
               'Your calm mind is the ultimate weapon against your challenges. — Bryant McGill',
               'Caring for myself is not self-indulgence, it is self-preservation. — Audre Lorde',
               'Self-care is a strategy, not a luxury. — Unknown',
               'Protect your peace. — Unknown',
               'Slow down to speed up. — Unknown',
               'Rest is productive. — Unknown',
               'Boundaries are self-respect in action. — Unknown',
               'You can’t pour from an empty cup. — Unknown',
               'Give yourself the same grace you give others. — Unknown',
               'Take a deep breath. You’re allowed to pause. — Unknown',
               'Your body hears everything your mind says. — Naomi Judd',
               'Make your mental health a priority. — Unknown'],
 'Sport': ['I float like a butterfly, sting like a bee. — Muhammad Ali',
           'Champions keep playing until they get it right.',
           'Winners train, losers complain.',
           'Every rep counts.',
           "Your body can stand almost anything; it's your mind you must convince.",
           'Train hard, stay humble.',
           'The pain you feel today is the strength you gain tomorrow.',
           'Strong mind, strong body.',
           'Don’t limit your challenges; challenge your limits.',
           'Sweat is your body crying for progress.',
           'Discipline beats motivation.',
           'One more rep can change everything.',
           'I can accept failure, everyone fails at something. But I can’t accept not trying. — '
           'Michael Jordan',
           'Everything negative can be turned into motivation to succeed. — Kobe Bryant',
           'Success is a journey, not a destination. — Serena Williams',
           'If you are afraid of failure, you don’t deserve to be successful. — Charles Barkley',
           'Only the disciplined are free. — Eliud Kipchoge',
           'Train like it’s a privilege. — Unknown',
           'Earn your confidence. — Unknown',
           'Strong mind. Strong body. — Unknown',
           'Every day is a chance to get better. — Unknown',
           'Champions are made in the off-season. — Unknown',
           'The pain you feel today will be the strength you feel tomorrow. — Unknown',
           'It never gets easier; you just get better. — Greg LeMond',
           'Run the day. Don’t let it run you. — Unknown',
           'Suffer now and live the rest of your life as a champion. — Muhammad Ali',
           'Fall in love with the process. — Unknown'],
 'Discipline': ['Discipline is choosing what you want most over what you want now.',
                'Consistency creates results.',
                'Small steps every day lead to big changes.',
                'Discipline turns dreams into reality.',
                'Show up even when you don’t feel like it.',
                'Consistency beats intensity.',
                'Do it for your future self.',
                'Habits define your destiny.',
                'Stay focused; distractions can wait.',
                'Discipline is a superpower.',
                'You don’t get what you wish for; you get what you work for.',
                'Commitment is doing the work long after the mood has passed.',
                'Discipline is the bridge between goals and accomplishment. — Jim Rohn',
                'Freedom is born from discipline. — Jocko Willink',
                'We are what we repeatedly do. Excellence, then, is not an act, but a habit. — '
                'Aristotle',
                'The future depends on what you do today. — Mahatma Gandhi',
                'Self-discipline is the magic power that makes you virtually unstoppable. — Dan '
                'Kennedy',
                'Discipline is self-love. — Unknown',
                'Do it daily. — Unknown',
                'Consistency is a superpower. — Unknown',
                'Discipline is the difference between goals and results. — Unknown',
                'Win the morning, win the day. — Unknown',
                'First you make habits, then habits make you. — Unknown',
                'Do what you said you would do. — Unknown',
                'Discipline creates freedom. — Unknown',
                'Stick to the plan. — Unknown',
                'Show up. That’s the job. — Unknown'],
 'Friendship': ['True friendship has no distance.',
                'Friends are the family we choose.',
                'Good friends make life better.',
                'A true friend brings out the best in you.',
                'Real friends are rare treasures.',
                'Friendship grows through kindness.',
                'Laughter is the bond of friendship.',
                'A friend understands without words.',
                'Friends make the world brighter.',
                'Support, love, and loyalty define friendship.',
                'Good friends lift you higher.',
                'Friendship is a gift to cherish.',
                'A friend is one of the nicest things you can have, and one of the best things you '
                'can be. — Douglas Pagels',
                'Friendship doubles joys and halves griefs. — Francis Bacon',
                'A real friend is one who walks in when the rest of the world walks out. — Walter '
                'Winchell',
                'The only way to have a friend is to be one. — Ralph Waldo Emerson',
                'True friendship comes when the silence between two people is comfortable. — David '
                'Tyson',
                'Good friends are good medicine. — Unknown',
                'Friendship is built on trust and time. — Unknown',
                'A friend makes the good times better and the hard times easier. — Unknown',
                'Friends are proof you’re not alone. — Unknown',
                'Real friends don’t compete; they connect. — Unknown',
                'Friendship is the comfort of knowing you’re understood. — Unknown',
                'Kindness is the language of friendship. — Unknown',
                'Be the friend you want. — Unknown',
                'True friends feel like home. — Unknown',
                'A little check-in goes a long way. — Unknown'],
 'Resilience': ['Fall seven times, stand up eight.',
                'Storms make trees take deeper roots.',
                'Hard times create strong people.',
                'Pain is temporary, strength is forever.',
                'The struggle you’re in today builds your tomorrow.',
                'Not all storms come to disrupt; some come to clear your path.',
                'Keep fighting; better days are ahead.',
                'You are stronger than you think.',
                'Rise after every fall.',
                'Every setback is a setup for a comeback.',
                'Your resilience defines your journey.',
                'Hold on; your breakthrough is coming.',
                'That which does not kill us makes us stronger. — Friedrich Nietzsche',
                'Tough times never last, but tough people do. — Robert Schuller',
                'The human capacity for burden is like bamboo—far more flexible than you’d ever '
                'believe. — Jodi Picoult',
                'When you have exhausted all possibilities, remember this: you haven’t. — Thomas '
                'Edison',
                'Our greatest glory is not in never falling, but in rising every time we fall. — '
                'Confucius',
                'Keep going. You’re closer than you think. — Unknown',
                'Adapt. Adjust. Overcome. — Unknown',
                'Your comeback will be stronger than your setback. — Unknown',
                'Pressure builds diamonds. — Unknown',
                'Hard days build strong minds. — Unknown',
                'Strength grows in the moments you think you can’t go on but keep going. — Unknown',
                'Turn wounds into wisdom. — Oprah Winfrey',
                'Rock bottom became the solid foundation on which I rebuilt my life. — J. K. '
                'Rowling',
                'Don’t count the days; make the days count. — Muhammad Ali',
                'Fall down seven times, stand up eight. — Japanese proverb'],
 'Creativity': ['Creativity is intelligence having fun.',
                'Everything you can imagine is real.',
                'Ideas grow when shared.',
                'Creativity thrives in curiosity.',
                'Think differently; the world needs your ideas.',
                'Innovation begins with imagination.',
                'Let your mind wander—magic happens there.',
                'Create without fear.',
                "Mistakes are proof you're trying.",
                'Break the rules; make your own.',
                'Your voice is unique—use it.',
                'Art is freedom in motion.',
                'Imagination is more important than knowledge. — Albert Einstein',
                'Creativity takes courage. — Henri Matisse',
                'Art enables us to find ourselves and lose ourselves at the same time. — Thomas '
                'Merton',
                'You can’t use up creativity. The more you use, the more you have. — Maya Angelou',
                'The chief enemy of creativity is ‘good’ sense. — Pablo Picasso',
                'Create first, judge later. — Unknown',
                'Done is better than perfect. — Unknown',
                'Curiosity fuels creativity. — Unknown',
                'Make something today. — Unknown',
                'Start with what you have. — Unknown',
                'Creativity is allowing yourself to make mistakes. Art is knowing which ones to '
                'keep. — Scott Adams',
                'Inspiration exists, but it has to find you working. — Pablo Picasso',
                'Everything you can imagine is real. — Pablo Picasso',
                'Creativity is a wild mind and a disciplined eye. — Dorothy Parker',
                'Art washes away from the soul the dust of everyday life. — Pablo Picasso'],
 'Career': ['The future depends on what you do today.',
            'Success comes to those who are too busy to be looking for it.',
            'Great careers are built step by step.',
            'Invest in your skills; they never fade.',
            'Your career grows as you grow.',
            'Be valuable, not just available.',
            'Show your work; the world needs your talent.',
            'Opportunities favor the prepared.',
            'Ambition is the first step to success.',
            'Hard work beats luck.',
            "Build a career you're proud of.",
            'Learning is the path to mastery.',
            'Choose a job you love, and you will never have to work a day in your life. — '
            'Confucius',
            'The only way to do great work is to love what you do. — Steve Jobs',
            'Strive not to be a success, but rather to be of value. — Albert Einstein',
            'If you’re offered a seat on a rocket ship, don’t ask what seat. Just get on. — Sheryl '
            'Sandberg',
            'Do not wait to strike till the iron is hot; but make it hot by striking. — William '
            'Butler Yeats',
            'Skills pay the bills. — Unknown',
            'Be so good they can’t ignore you. — Steve Martin',
            'Work on your craft, not your ego. — Unknown',
            'Reputation is built in years and lost in seconds. — Unknown',
            'Your network is your net worth. — Unknown',
            'Success is where preparation and opportunity meet. — Bobby Unser',
            'Opportunities multiply as they are seized. — Sun Tzu',
            'Quality means doing it right when no one is looking. — Henry Ford',
            'Under-promise and over-deliver. — Unknown',
            'Keep learning. Stay valuable. — Unknown'],
 'Gratitude': ['Gratitude turns what we have into enough.',
               'A grateful heart attracts miracles.',
               'Appreciation unlocks abundance.',
               'Gratitude changes your state instantly.',
               'Count blessings, not problems.',
               'Thankfulness opens the door to joy.',
               'A grateful mindset transforms life.',
               'Gratitude is a magnet for positivity.',
               'See the good—it’s always there.',
               'The more you appreciate, the more you receive.',
               'Gratitude makes life richer.',
               'A grateful heart is a peaceful heart.',
               'Gratitude is not only the greatest of virtues, but the parent of all the others. — '
               'Cicero',
               'The more thankful I became, the more my bounty increased. — Oprah Winfrey',
               'Enjoy the little things, for one day you may look back and realize they were the '
               'big things. — Robert Brault',
               'Silent gratitude isn’t much use to anyone. — G. B. Stern',
               'Gratitude turns what we have into enough, and more. — Melody Beattie',
               'Gratitude is a shortcut to joy. — Unknown',
               'Gratitude changes everything. — Unknown',
               'Be thankful for small things. — Unknown',
               'Gratitude turns ordinary days into thanksgivings. — Unknown',
               'Appreciate what you have while working for what you want. — Unknown',
               'Gratitude is the healthiest of all human emotions. — Zig Ziglar',
               'Gratitude is riches. Complaint is poverty. — Doris Day',
               'Enjoy the now. Be grateful. — Unknown',
               'Gratitude makes room for more. — Unknown',
               'Say thank you more often. — Unknown']}
