# quotes.py
# -----------------------------
# Quote Master Bot – Quote Database (TR & EN) – 1000+ quotes
# Includes: TR/EN quote dictionaries + Special Days support
# -----------------------------

from __future__ import annotations
import random
import datetime
from typing import Dict, List, Optional, Tuple, Any

QUOTES_TR = {'Aile': ['Aile, sığınaktır.',
          'Aile, köklerindir.',
          'Aile, sevginin evidir.',
          'Aile, en büyük destektir.',
          'Aile, birlikte güçlenmektir.',
          'Aile, emek ister.',
          'Aile, güven demektir.',
          'Aile, paylaşınca büyür.',
          'Aile, hataları affetmeyi öğrenir.',
          'Aile, kalbin yurdudur.',
          'Aile, birlikte iyileşir.',
          'Aile, sabırla kurulur.',
          'Aile, küçük anlardan oluşur.',
          'Aile, birlikte gülmektir.',
          'Aile, zor günlerde yanındadır.',
          'Aile, değerleri taşır.',
          'Aile, birbirini büyütür.',
          'Aile, sevgiyle onarır.',
          'Aile, şefkatin kaynağıdır.',
          'Aile, hatırlanmaktır.',
          'Aile, anlayışla güzelleşir.',
          'Aile, evden daha fazlasıdır.',
          'Aile, birliktir.',
          'Aile, birlikte yaşanan hikâyedir.',
          'Aile, kalpten kalbe bağdır.',
          'Aile, huzurun adresidir.',
          'Aile, her şeyin başıdır.'],
 'Aşk': ['Sevgi, paylaştıkça çoğalır.',
         'Aşk, küçük bir tebessümle başlar.',
         'Sevgi emektir; ilgi ister.',
         'Kalpten gelen söz, kalbe gider.',
         'Aşk, aynı yöne bakabilmektir.',
         'Sevgi, sabırla büyür.',
         'Birlikte gülmek, en güzel bağdır.',
         'Aşk, güvenin en sıcak hâlidir.',
         'Sevgi, hayatın en güçlü ilacıdır.',
         'Aşk, her gün yeniden seçmektir.',
         'Sevgi, detaylarda saklıdır.',
         'Aşk, iki kalbin ortak ritmidir.',
         'Sevgi, hatırlanmaktır.',
         'Aşk, özünde cesarettir.',
         'Sevgi, iyileştirir.',
         'Aşk, nazik olmaktır.',
         'Sevgi, konuşmadan da anlaşmaktır.',
         'Aşk, kalbin disiplinidir.',
         'Sevgi, beklentisiz verince güzelleşir.',
         'Aşk, birlikte büyümektir.',
         'Sevgi, en doğru yatırım.',
         'Aşk, bir insanı daha iyi hâle getirir.',
         'Sevgi, kalbi yumuşatır.',
         'Aşk, iyi niyetle güçlenir.',
         'Sevgi, günün ışığı gibidir.',
         'Aşk, fedakârlık değil; denge ister.',
         'Sevgi, hayatı anlamlı kılar.'],
 'Başarı': ['Başarı tesadüf değildir; emek ister.',
            'Hazırlık şansı yakalayınca başarı ortaya çıkar.',
            'Ne kadar çok çalışırsan o kadar şanslı olursun.',
            'Başarı, küçük zaferlerin toplamıdır.',
            'Her başarının arkasında görünmeyen bir çaba vardır.',
            'Doğru zamanda doğru yerde olmak değil; doğru kişi olmak önemlidir.',
            'Kazanmak istiyorsan önce inanmalısın.',
            'Başarı bazen sadece bir adım daha devam etmektir.',
            'Fırsatlar hazırlanmış zihinlere gelir.',
            'Pes etmeyenler en sonunda kazanır.',
            'Disiplin olmadan başarı olmaz.',
            'Yavaş ilerlemek durmaktan iyidir.',
            'Başarı, hazırlık ile fırsatın buluştuğu yerdir. — Seneca',
            'Kazananlar asla vazgeçmez; vazgeçenler asla kazanamaz. — Vince Lombardi',
            'Başarı, her gün tekrarlanan küçük çabaların toplamıdır. — Robert Collier',
            'Fırsatlar kendiliğinden olmaz; sen yaratırsın. — Chris Grosser',
            'Başarı, çoğunlukla başkalarının pes ettiği noktadan sonra gelir. — William Feather',
            'Başarı, düşe kalka yürümeye devam etmektir. — Anonim',
            'İstikrar, gizli hızdır. — Anonim',
            'Başarı, doğru alışkanlıkların yan ürünüdür. — Anonim',
            'İyi şeyler zaman alır; harika şeyler daha çok. — Anonim',
            'Planla, uygula, geliştir. — Anonim',
            'Başarı, fırsat geldiğinde hazır olmaktır. — Benjamin Disraeli',
            'Başarısızlık, yeniden başlama fırsatıdır. — Henry Ford',
            'Başarı, kendini aşma sanatıdır. — Anonim',
            'En büyük başarı, vazgeçmemeyi seçmektir. — Anonim',
            'Yapabileceğini kanıtlamak için tek kişiye ihtiyacın var: kendin. — Anonim'],
 'Bilgelik': ['Bilgelik, doğru soruyu sorabilmektir.',
              'Bilgelik, deneyimi anlamlandırmaktır.',
              'Bilgelik, sakin kalabilmektir.',
              'Bilgelik, az konuşup çok görmektir.',
              'Bilgelik, egoyu azaltmaktır.',
              'Bilgelik, dinlemeyi bilmektir.',
              'Bilgelik, seçimlerinin sonucunu görmektir.',
              'Bilgelik, basitliği sevmektir.',
              'Bilgelik, ölçülü olmaktır.',
              'Bilgelik, öğrenmeye açık kalmaktır.',
              'Bilgelik, değişimi kabullenmektir.',
              'Bilgelik, sabırla büyür.',
              'Bilgelik, kendini tanımaktır.',
              'Bilgelik, affedebilmektir.',
              'Bilgelik, yarayı ders yapmaktır.',
              'Bilgelik, sakin bir güçtür.',
              'Bilgelik, şükürle derinleşir.',
              'Bilgelik, merhamettir.',
              'Bilgelik, sınırları bilmektir.',
              'Bilgelik, iyi niyetle birleşir.',
              'Bilgelik, uzun vadeyi görmektir.',
              'Bilgelik, ölçülü cesarettir.',
              'Bilgelik, kalbi yormamaktır.',
              'Bilgelik, kendine dürüst olmaktır.',
              'Bilgelik, anı yaşamaktır.',
              'Bilgelik, yargıyı azaltmaktır.',
              'Bilgelik, doğru zamanda durmaktır.'],
 'Cesaret': ['Cesaret, korkuya rağmen adım atmaktır.',
             'Korku varsa büyüme vardır.',
             'Cesaret, ilk adımı atmaktır.',
             'Konfor alanı güzel ama orada mucize yok.',
             'Hayır diyebilmek de cesarettir.',
             'Hata yapma hakkın var; dene.',
             'Cesaret, her gün yeniden başlar.',
             'Risk, bazen ilerlemenin bedelidir.',
             'Cesaret, karanlıkta yürümektir.',
             'İçindeki sesi dinle.',
             'Cesaret, kendine sadık kalmaktır.',
             'Zor konuşmaları erteleme.',
             'Cesaret, sınır koymaktır.',
             'Cesaret, yardım istemektir.',
             'Cesaret, yeniden denemektir.',
             'Cesaret, eleştiriye rağmen üretmektir.',
             'Cesaret, kırılgan olabilmektir.',
             'Cesaret, karar almaktır.',
             'Cesaret, belirsizliği kabul etmektir.',
             'Cesaret, korkunun üzerine gitmektir.',
             'Küçük cesaretler büyük hayat yapar.',
             'Cesaret, sabırla birleşince güç olur.',
             'Cesaret, değişimi seçmektir.',
             'Cesaret, vazgeçmemektir.',
             'Cesaret, kendini affetmektir.',
             'Cesaret, doğruyu söylemektir.',
             'Cesaret, iyiliği sürdürmektir.'],
 'Dayanıklılık': ['Vazgeçmeyen kazanır.',
                  'Her yara seni daha güçlü yapar.',
                  'Düşmek kaderindir, kalkmak tercihindir.',
                  'Zorluklar karakteri şekillendirir.',
                  'Her karanlık gecenin bir sabahı vardır.',
                  'Sabrın sonu daima güçtür.',
                  'Kırılmadan güçlenemezsin.',
                  'En zor anlarda bile ilerle.',
                  'Yıkılmadığın sürece yenilmedin.',
                  'Güçlü insanlar, savaşarak güçlenenlerdir.',
                  'Fırtına geçer, gökyüzü açılır.',
                  'Her nefes bir umuttur.',
                  'Beni öldürmeyen şey beni güçlendirir. — Friedrich Nietzsche',
                  'Karanlığın en yoğun olduğu an, şafak sökmeden hemen öncedir. — Thomas Fuller',
                  'Her zorluk, içinde bir fırsat taşır. — Albert Einstein',
                  'Umudu olan için hiçbir yol kapanmaz. — Desmond Tutu',
                  'Dayanıklılık, pes etmeyenlerin sessiz zaferidir. — Unknown',
                  'Fırtınalar geçer; sen kalırsın. — Anonim',
                  'Bugün zor, yarın güçlü. — Anonim',
                  'Yaraların, haritan olur. — Anonim',
                  'Yük ağırsa, güçleniyorsun demektir. — Anonim',
                  'Sabır, sessiz cesarettir. — Anonim',
                  'Kırılınca değil, vazgeçince biter. — Anonim',
                  'Düşünce değil, kalkışın önemli. — Anonim',
                  'Yeniden başlamak da bir güçtür. — Anonim',
                  'Her gün biraz daha dayanıklı ol. — Anonim',
                  'Direnç, tekrar tekrar denemektir. — Anonim'],
 'Disiplin': ['Disiplin, başarının gizli anahtarıdır.',
              'Küçük disiplinler büyük zaferler getirir.',
              'İrade varsa yol vardır.',
              'Disiplin, özgürlüğün başlangıcıdır.',
              'Her gün tekrar eden küçük alışkanlıklar seni değiştirir.',
              'Motivasyon gelir gider; disiplin kalır.',
              'Kendini yönetebilmek en büyük başarıdır.',
              'İstikrarlı olan her zaman kazanır.',
              'Zor olanı yapmak karakteri inşa eder.',
              'Disiplin, gelecekteki senin için bugünkü fedakarlıktır.',
              'Ne yapman gerektiğini bilmek değil, yapmak önemlidir.',
              'Disiplinli olan yorulmaz; güçlenir.',
              'Disiplin, hedeflerle başarı arasındaki köprüdür. — Jim Rohn',
              'Özgürlük, disiplinle başlar. — Jocko Willink',
              'Biz, tekrarladığımız şeyiz; mükemmellik bir eylem değil, alışkanlıktır. — Aristoteles',
              'İrade, çalıştırıldıkça güçlenen bir kas gibidir. — Buddha',
              'Disiplin olmadan hiçbir başarı sürdürülebilir değildir. — John C. Maxwell',
              'Rutin kur, özgür ol. — Anonim',
              'Az ama her gün. — Anonim',
              'Disiplin, duyguların değil kararların eseridir. — Anonim',
              'İstek geçer; alışkanlık kalır. — Anonim',
              'Zor olanı seçmek, kolaylaşır. — Anonim',
              'Kendine söz ver; tut. — Anonim',
              'İstikrarlı ol; mucizeyi bekleme. — Anonim',
              'Bugün yaptıkların, yarınını yazar. — Anonim',
              'Disiplin, sessiz bir ‘evet’tir. — Anonim',
              'Küçük kurallar, büyük sonuçlar doğurur. — Anonim'],
 'Dostluk': ['Gerçek dostluk mesafe tanımaz.',
             'Dostluk iki beden içinde yaşayan tek ruhtur.',
             'Yanında yürüyen bir dost, yoldaki yükü hafifletir.',
             'Dost, zor günde belli olur.',
             'Gerçek arkadaşlık zamanla değil, samimiyetle ölçülür.',
             'Bir dost bir dünyadır.',
             'Dostluğun değeri paha biçilemez.',
             'Güven, dostluğun temelidir.',
             'İyi arkadaş, hayatı güzelleştirir.',
             'Birlikte gülmek en güzel bağdır.',
             'Dost, kalbinin aynasıdır.',
             'Yanında huzur bulduğun kişi dostundur.',
             'Dost, bütünün diğer yarısıdır. — Platon',
             'Gerçek dostluk, iki beden içinde yaşayan tek ruhtur. — Aristoteles',
             'Bir dost edinmek istiyorsan, bir dost ol. — Ralph Waldo Emerson',
             'Dostluk, mutluluğu artırır, acıyı azaltır. — Thomas Aquinas',
             'Gerçek dostluk, iki kişi arasındaki sessizliği bile anlamlı kılar. — David Tyson',
             'Dost, omzuna yük değil; omuz verir. — Anonim',
             'İyi dost, iyi aynadır. — Anonim',
             'Samimiyet, dostluğun dili. — Anonim',
             'Kalpten gelen, kalbe gider. — Anonim',
             'Dostluk, paylaşınca çoğalan tek şeydir. — Anonim',
             'Gerçek dost, başarıda değil; yorgunlukta yanında olandır. — Anonim',
             'Bir mesaj bazen ‘buradayım’ demektir. — Anonim',
             'Dostluk, küçük inceliklerde saklıdır. — Anonim',
             'Güven varsa mesafe sorun olmaz. — Anonim',
             'İyi arkadaşlık, iyi niyetin uzun halidir. — Anonim'],
 'Hayat': ['Hayat, cesur olana fırsatlar sunar.',
           'Dün geçti, yarın bilinmez; bugün yaşanır.',
           'Mutluluk, paylaştıkça çoğalır.',
           'Hayat kısa, onu anlamlı yapan sensin.',
           'Her gün yeni bir başlangıçtır.',
           'Zaman geri gelmez; iyi kullan.',
           'Hayatın ritmini sen belirlersin.',
           'Düşüncelerin hayatını şekillendirir.',
           'Bazen en büyük yolculuk, kendine yaptığındır.',
           'Hayat, seçimlerin toplamıdır.',
           'Sadelik çoğu zaman mutluluğun anahtarıdır.',
           'Bugünü güzel yaşa; yarın belirsizdir.',
           'Hayat, biz başka planlar yaparken başımıza gelenlerdir. — John Lennon',
           'Dünyada görmek istediğin değişim ol. — Mahatma Gandhi',
           'İnsanların çoğu, mutlu olmaya karar verdikleri ölçüde mutludur. — Abraham Lincoln',
           'Yaşam cesurları ödüllendirir. — Virgil',
           'Önemli olan, yıllara ne kadar hayat sığdırdığın. — Abraham Lincoln',
           'Hayat, nefes almak değil; nefes kesen anlar biriktirmektir. — Anonim',
           'Basit yaşa, derin hisset. — Anonim',
           'Her şey geçer; bu da geçer. — Anonim',
           'Bugün, kalan hayatının ilk günü. — Anonim',
           'Hayat, küçük seçimlerin büyük toplamıdır. — Anonim',
           'Mutluluk, yolun üzerindedir; varışta değil. — Buddha',
           'Hayatını değiştirmek istiyorsan alışkanlıklarını değiştir. — Anonim',
           'İyi bir hayat, iyi niyetle başlar. — Anonim',
           'Yaşadıkların değil, onlara verdiğin anlam seni şekillendirir. — Anonim',
           'Her sabah yeniden doğarsın; bugün ne yapacağın önemlidir. — Buddha'],
 'Kendine iyi bak': ['Kendine iyi bakmak, hayata iyi bakmaktır.',
                     'Önce sen iyi ol ki dünya sana iyi gelsin.',
                     'Bedenine ve zihnine iyi davran.',
                     'Kendini ihmal etmek, geleceğini ihmal etmektir.',
                     'Dinlenmek de üretmektir.',
                     'İyileşmek zaman ister; kendine sabırlı davran.',
                     'Sen değerlisin, kendine öyle davran.',
                     'Ruhunu beslemeyi unutma.',
                     'Kendine şefkat göster.',
                     'Duygularını bastırma; anlamaya çalış.',
                     'Zihnini temizle, enerjin tazelensin.',
                     'Kendine ayırdığın zaman asla boşa gitmez.',
                     'Kendine karşı nazik ol; ruhun da bunu duyar. — Buddha',
                     'Bedenin, ruhunun evindir; ona iyi bak. — Seneca',
                     'Zihninize yatırım yapmak, yapacağınız en iyi yatırımdır. — Benjamin Franklin',
                     'Kendini sevmek, ömür boyu sürecek bir aşkın başlangıcıdır. — Oscar Wilde',
                     'İç huzur, hayattaki en büyük servettir. — Dalai Lama',
                     'Hayır demek, kendine evet demektir. — Anonim',
                     'Dinlenmek tembellik değil, bakımın bir parçasıdır. — Anonim',
                     'Kendine iyi davran; seninle 24 saat birlikte olan sensin. — Anonim',
                     'Yeterince iyi olmak da bir başarıdır. — Anonim',
                     'Zihnin yorulduysa, bedenin dinlenmesi yetmez. — Anonim',
                     'Kendini kıyaslama; kendi yolunda yürü. — Anonim',
                     'Nefes al, omuzlarını indir, devam et. — Anonim',
                     'İyileşmek, aceleye gelmez. — Anonim',
                     'Küçük rutinler, büyük huzur getirir. — Anonim',
                     'Kendine şefkat, gücün en sessiz halidir. — Anonim'],
 'Liderlik': ['Liderlik, örnek olmaktır.',
              'İyi lider, önce dinler.',
              'Liderlik unvan değil, etkidir.',
              'İnsanları yükselt; sonuçlar gelir.',
              'Karar almak cesaret ister.',
              'Vizyon, liderin pusulasıdır.',
              'Güven, liderliğin temelidir.',
              'Hatalarını sahiplenen lider büyür.',
              'Takımını koruyan lider kazanır.',
              'Lider, sorumluluktan kaçmaz.',
              'İyi lider, net hedef koyar.',
              'İlham veren lider iz bırakır.',
              'Liderlik, zor zamanda belli olur.',
              'Adalet, liderliğin omurgasıdır.',
              'Lider, egosunu değil ekibini büyütür.',
              'Başarıyı paylaşan lider saygı görür.',
              'Lider, eleştiriyi fırsata çevirir.',
              'İyi lider, belirsizliği yönetir.',
              'Lider, sakinliği yayar.',
              'Liderlik, tutarlılıktır.',
              'Söz değil, davranış lider yapar.',
              'Lider, gelişimi teşvik eder.',
              'Lider, doğru soruları sorar.',
              'Liderlik, hizmet etmektir.',
              'Netlik, kararsızlıktan güçlüdür.',
              'Lider, örnek disiplin kurar.',
              'Bir liderin gücü, ekibinin gücüdür.'],
 'Motivasyon': ['Zorluklar, güçlü insanları yaratır.',
                'Başlamak için mükemmel olmak zorunda değilsin.',
                'Devam eden kazanır.',
                'Bugün attığın küçük bir adım, yarın büyük bir değişim yaratır.',
                'Kendine inan; gerisi zaten gelir.',
                'Başlamaktan daha zor olan tek şey, vazgeçmemektir.',
                'Her gün biraz daha iyi ol.',
                'Hayallerine giden yol cesaret ister.',
                'Başarıya giden yol, konfor alanının dışından geçer.',
                'Hedefine odaklan, gürültüyü sustur.',
                'Güçlü olmanın en iyi yolu, zor zamanlardan geçmektir.',
                'Yapabileceğini düşünüyorsan, zaten yarı yolun dasın.',
                'Bugün yapabildiğini yap; yarın daha fazlasını yaparsın.',
                'Ne kadar yavaş gittiğin önemli değil, durmadığın sürece yol alırsın. — Konfüçyüs',
                'Hayatta en büyük zafer, hiç düşmemek değil; her düştüğünde yeniden ayağa kalkmaktır. — Nelson Mandela',
                'Yapabileceğine inan; gerisi zaten kendiliğinden gelecektir. — Theodore Roosevelt',
                'Güçlü olan, zayıf anında pes etmeyendir. — Vince Lombardi',
                'Bugünün şüpheleri, yarının gerçeklerini sınırlar. — Franklin D. Roosevelt',
                'İlk adım, en büyük adımdır. — Anonim',
                'Bugün vazgeçmezsen, yarın gurur duyarsın. — Anonim',
                'Cesaret, korkuya rağmen devam etmektir. — Anonim',
                'Başlamak, yarı yarıya bitirmektir. — Anonim',
                'Yol uzun diye dönme; her adım seni yaklaştırır. — Anonim',
                'Bin millik yolculuk tek bir adımla başlar. — Lao Tzu',
                'Yaşamak cesaret işidir. — Cemal Süreya',
                'Yıldızlara ulaşmak için gözlerini yukarı kaldır. — Anonim',
                'Hayal ettiğin şey için çalış; şikayet için değil. — Anonim',
                'İmkânsız, sadece bir fikirden ibarettir. — Anonim'],
 'Para & Finans': ['Para araçtır; amaç değil.',
                   'Harca, ama bilinçle harca.',
                   'Bütçe, özgürlüğe giden plan.',
                   'Küçük tasarruflar büyük fark yaratır.',
                   'Gelir kadar gider de yönetilir.',
                   'Borç, yarının emeğidir.',
                   'Risk yönetimi, akıllı cesarettir.',
                   'Biriken para değil, biriken disiplin kazanır.',
                   'Yatırım bilgi ister; acele etmez.',
                   'Çeşitlilik, riski azaltır.',
                   'Önce birikim, sonra harcama.',
                   'Fırsat maliyetini unutma.',
                   'Kazanç kadar korunma da önemlidir.',
                   'Finansal sağlık, alışkanlıktır.',
                   'Kısa haz, uzun hedefi çalmasın.',
                   'Parayı yönet; para seni yönetmesin.',
                   'Plan yoksa para kayar gider.',
                   'Değer üret; kazanç gelir.',
                   'Zenginlik, seçenek sahibi olmaktır.',
                   'Acil durum fonu, huzurdur.',
                   'Kararlarını duyguyla değil veriyle al.',
                   'İstikrar, finansın gizli gücü.',
                   'Küçük harcamalar büyük delik açar.',
                   'En iyi yatırım, kendindir.',
                   'Para konuşur; sen dinle.',
                   'Gelir artır, gider kontrol et.',
                   'Finansal hedef, net olmalı.'],
 'Sabır': ['Sabır, zamanın öğretmenidir.',
           'Sabır, güçlülerin sessizliğidir.',
           'Beklemek değil; olgunlaşmaktır sabır.',
           'Sabır, sürecin parçasıdır.',
           'Acele eden yorulur; sabreden kazanır.',
           'Sabır, nefesi düzene sokar.',
           'Her şeyin bir zamanı var.',
           'Sabır, küçük adımlarla yürümektir.',
           'Tohum hemen meyve vermez.',
           'Sabır, kontrol edemediğine alan açmaktır.',
           'Sabır, duygu yönetimidir.',
           'Sabır, hedefe sadakattir.',
           'Sabır, kararlılığın kardeşidir.',
           'Sabır, duayı eylemle birleştirir.',
           'Sabır, kendine şefkattir.',
           'Sabır, telaşı azaltır.',
           'Sabır, uzun oyunu oynar.',
           'Sabır, olgunluk belirtisidir.',
           'Sabır, ağır ama sağlam ilerler.',
           'Sabır, öğrenmenin bir türüdür.',
           'Sabır, huzurun kapısıdır.',
           'Sabır, zor günlerin ilacı.',
           'Sabır, büyümenin bedeli.',
           'Sabır, aceleyi terbiye eder.',
           'Sabır, umutla beslenir.',
           'Sabır, sakin bir güçtür.',
           'Sabır, vazgeçmemektir.'],
 'Spor': ['Kelebek gibi uçar, arı gibi sokarım. — Muhammed Ali',
          'Zorluklar şampiyonları belirler.',
          'Ter, başarıya açılan kapının anahtarıdır.',
          'Zafer, hazırlananlarındır. — Herodot',
          'Her tekrar seni güçlendirir.',
          'Disiplin, sporcunun gerçek gücüdür.',
          'Sınırlarını zorla; potansiyelini keşfet.',
          'Bugünün acısı yarının gücüdür.',
          'Spor, bedenin ve zihnin uyumudur.',
          'Pes etme, bir tekrar daha yap.',
          'Koşarken düşünceler değil, adımlar önemlidir.',
          'Güçlü olmak bir tercih meselesidir.',
          'Antrenman yalan söylemez.',
          'Kazanmak için önce kaybetmeyi öğrenmelisin. — Serena Williams',
          'Başarısızlığı kabul edebilirim ama denememeyi asla. — Michael Jordan',
          'Zorlu anlar güçlü insanlar yaratır. — Kobe Bryant',
          'Hiçbir şey, çalışanı durduramaz. — Eliud Kipchoge',
          'Acı geçicidir, pes etmek kalıcıdır. — Lance Armstrong',
          'Bugün antrenman, yarın özgüven. — Anonim',
          'Koşu biter; karakter kalır. — Anonim',
          'Her kilometre, zihnini de güçlendirir. — Anonim',
          'Şampiyonluk, sıradan günlerde kazanılır. — Anonim',
          'Isınma bir bahane değil; bir disiplindir. — Anonim',
          'Acıyı sevme; onunla barış. — Anonim',
          'Yorulduğunda durma; yavaşla. — Anonim',
          'Güç, tekrarlarla inşa edilir. — Anonim',
          'En iyi antrenman, yaptığındır. — Anonim',
          'Bugün ter, yarın gurur. — Anonim'],
 'Yaratıcılık': ['Yaratıcılık zekânın eğlenmesidir.',
                 'Fikirler özgür bırakıldığında değer kazanır.',
                 'Hayal gücü her şeydir.',
                 'Her büyük eser bir fikirle başlar.',
                 'Merak, yaratıcılığın yakıtıdır.',
                 'Hayal kur; sınırlar ötesi seni bekler.',
                 'Yaratıcılık risk alınca ortaya çıkar.',
                 'Renklerin dili vardır; seninle konuşur.',
                 'Farklı düşünmek cesaret ister.',
                 'İlham her yerde; yeter ki bakmayı bil.',
                 'Basitlik en yaratıcı çözümdür.',
                 'Her yanlış deneme yeni bir keşiftir.',
                 'Hayal gücü bilgiden daha önemlidir. — Albert Einstein',
                 'Yaratıcılık bulaşıcıdır, yay. — Albert Einstein',
                 'Sanat, görünmeyeni görünür kılar. — Paul Klee',
                 'Yaratıcılık cesaret ister. — Henri Matisse',
                 'Fikirler, paylaşıldıkça büyür. — George Bernard Shaw',
                 'Yeni fikir, yeni yol demektir. — Anonim',
                 'Merak et; öğren; üret. — Anonim',
                 'Fikirler, cesaretle şekillenir. — Anonim',
                 'Yaratıcılık, ‘ya şöyle olsaydı?’ sorusudur. — Anonim',
                 'İlham bekleme; üretince gelir. — Anonim',
                 'Çizgiyi boz; yolu bul. — Anonim',
                 'Basit düşün, farklı yap. — Anonim',
                 'Yap ve geliştir; mükemmeli bekleme. — Anonim',
                 'Hata, denemenin imzasıdır. — Anonim',
                 'Hayal kurmak, tasarlamanın başlangıcıdır. — Anonim'],
 'Zihin & Mindset': ['Zihnin nereye giderse sen oraya gidersin.',
                     'Düşünceler, duyguları doğurur.',
                     'Odak, enerjiyi büyütür.',
                     'Olumsuz iç sesi yakala, değiştir.',
                     'Zihin eğitilir; kader değildir.',
                     'Bugün düşündüğün, yarınki senin.',
                     'Şikâyet değil çözüm üret.',
                     'Kontrol edebildiklerine odaklan.',
                     'Küçük zaferleri kutla.',
                     'İlerlemenin anahtarı, süreklilik.',
                     'Zihin netse yol netleşir.',
                     'Korku, çoğu zaman hayaldir.',
                     'İnanç, eylemi başlatır.',
                     'Zihnini besle, hayatın değişsin.',
                     'Karşılaştırma, huzuru çalar.',
                     'Bugün kendinle yarış.',
                     'Şimdiye dön; güç burada.',
                     'Çözüm odaklı düşün.',
                     'Esneklik, gücün bir türüdür.',
                     'Öz disiplin, zihin kasıdır.',
                     'Sabır, zihnin olgunluğu.',
                     'Endişe, geleceğe faiz ödemektir.',
                     'Olumlu rutinler, olumlu hayat.',
                     'Başarısızlık, geri bildirimdir.',
                     'Zihin sakinleşince her şey kolaylaşır.',
                     'Kendine konuştuğun gibi konuş.',
                     'Zihnini yönet; hayatını yönet.'],
 'Özgüven': ['Özgüven, kendine verdiğin sözdür.',
             'Kendine güven; öğrenerek büyürsün.',
             'Özgüven, deneyimle güçlenir.',
             'Cesaret, özgüvenin yakıtıdır.',
             'Kendini küçümseme; potansiyelin büyük.',
             'Bugün dene; yarın daha iyi olursun.',
             'Özgüven, iç sesini iyileştirmektir.',
             'Kendine saygı, özgüveni büyütür.',
             'Başarı, özgüveni besler.',
             'Özgüven, hata yapmaktan korkmamaktır.',
             'Kendinle barış; güçlenirsin.',
             'Kendine yatırım yap; güvenin artar.',
             'Özgüven, sınır koyabilmektir.',
             'Kendini tanı; gücünü gör.',
             'Özgüven, küçük kazanımlarla gelir.',
             'Kimse senin yerini tutamaz.',
             'Kendi değerini sen belirlersin.',
             'Özgüven, tutarlılıktır.',
             'Şüphe gelirse, kanıt üret: çalış.',
             'Özgüven, adım adım inşa edilir.',
             'Kendinle konuşma şeklin önemlidir.',
             'Yapabildiklerini hatırla.',
             'Zayıflıklarını kabul et; büyürsün.',
             'Özgüven, disiplinle güçlenir.',
             'Kendine inanmak bir karardır.',
             'Başla; güven arkadan gelir.',
             'Özgüven, kendin olmaktır.'],
 'Öğrenme': ['Öğrenmek, her gün yeniden başlamak.',
             'Merak, öğrenmenin motorudur.',
             'Yanlış, öğrenmenin öğretmenidir.',
             'Soru sormak zekânın işaretidir.',
             'Bilgi güçtür; uygulama daha büyük güç.',
             'Her kitap yeni bir dünyadır.',
             'Öğrenme, kendine yatırımdır.',
             'Usta olmak için acemi kalmayı bil.',
             'Her gün 1% geliş.',
             'Hata yap; ders al; devam et.',
             'Deneyim, en pahalı öğretmendir.',
             'Not al; tekrar et; kalıcı olur.',
             'Öğrenme, konfor alanını deler.',
             'Küçük adımlar büyük bilgi getirir.',
             'Yeni bir beceri, yeni bir kapıdır.',
             'Dinlemek, öğrenmenin yarısıdır.',
             'Sadeleştir; daha iyi anlarsın.',
             'Öğrenmek, özgürleştirir.',
             'Pratik, öğrenmeyi kalıcı yapar.',
             'Bilmediğini bilmek başlangıçtır.',
             'Mentor, yolu kısaltır.',
             'Öğrenmek cesaret ister.',
             'Başarı, öğrenme hızına bağlıdır.',
             'Her gün okuyan, her gün büyür.',
             'Öğrenme, asla geç kalmaz.',
             'Farklı bakış açıları ufku açar.',
             'Öğrenmek, geleceğini yazmaktır.'],
 'İş & Kariyer': ['Küçük adımlar büyük kariyerler yaratır.',
                  'İşini sev, başarı seni takip eder.',
                  'Hazırlık, fırsatla buluştuğunda başarı doğar.',
                  'Kariyer bir yolculuktur; acele etme, ilerle.',
                  'Bilgi, kariyerin en güçlü silahıdır.',
                  'Hedefi olan yolunu bulur.',
                  'Çalışmak, başarıya yapılmış bir yatırımdır.',
                  'Üretkenlik alışkanlıktan doğar.',
                  'Doğru ekip, büyük fark yaratır.',
                  'Kendine yatırım en değerli yatırımdır.',
                  'Fırsatlar çalışana gelir.',
                  'Ne kadar öğrenirsen o kadar büyürsün.',
                  'Geleceği tahmin etmenin en iyi yolu onu yaratmaktır. — Peter Drucker',
                  'Mükemmellik bir eylem değil, alışkanlıktır. — Aristoteles',
                  'Harika işler başarmanın tek yolu, yaptığın işi sevmektir. — Steve Jobs',
                  'Her uzman bir zamanlar acemiydi. — Helen Hayes',
                  'Karşılığını almak istiyorsan önce değer üret. — Zig Ziglar',
                  'İtibar, en uzun vadeli yatırımdır. — Anonim',
                  'Sonuç değil süreç yönet. — Anonim',
                  'İyi iş, iyi alışkanlıktan çıkar. — Anonim',
                  'Bugün öğrendiğin, yarın maaşına dönüşür. — Anonim',
                  'İyi ekip, iyi liderlikle büyür. — Anonim',
                  'Profesyonellik, sözünde durmaktır. — Anonim',
                  'Az konuş, çok teslim et. — Anonim',
                  'Değer üret; görünür olursun. — Anonim',
                  'Sabır + emek = kariyer. — Anonim',
                  'Kariyer, bir gecede değil; her gün inşa edilir. — Anonim'],
 'Şükran': ['Şükür, sahip olduklarını çoğaltır.',
            'Minnettarlık huzurun kapısıdır.',
            'Teşekkür etmek ruhu hafifletir.',
            'Bugün için şükret; yarın için umut et.',
            'Şükreden insan, huzuru bulur.',
            'Küçük şeylere minnet etmek büyüklüğü getirir.',
            'Hayat güzeldir; fark edene.',
            'Şükür kalbi yumuşatır.',
            'Daha az şikayet, daha çok şükür.',
            'Sahip olduklarını fark et; her şey değişir.',
            'Mutluluk şükürle başlar.',
            'Teşekkür, en sade mutluluktur.',
            'Minnettarlık, erdemlerin en büyüğüdür. — Cicero',
            'Şükran, mutluluğun temelidir. — B. K. S. Iyengar',
            'Ne kadar şükredersen, şükredecek o kadar çok şey bulursun. — Oprah Winfrey',
            'Teşekkür etmek, ruhun en zarif sanatıdır. — Voltaire',
            'Mutlu insanların şükrettiği değil, şükredenlerin mutlu olduğu söylenir. — Unknown',
            'Şükür, yüreği genişletir. — Anonim',
            'Bugünün küçük sevinçlerini fark et. — Anonim',
            'Teşekkür, görünmeyeni görünür kılar. — Anonim',
            'Azla mutlu olabilen, çokla taşar. — Anonim',
            'Şükür, huzurun en kısa yoludur. — Anonim',
            'Her gün bir şeye teşekkür et. — Anonim',
            'İyiliği gör; çoğalır. — Anonim',
            'Elindekini sev; büyür. — Anonim',
            'Şükür, kalbin nefesidir. — Anonim',
            'Paylaşınca bereket artar. — Anonim']}

QUOTES_EN = {'Career': ['The future depends on what you do today.',
            'Success comes to those who are too busy to be looking for it.',
            'Great careers are built step by step.',
            'Invest in your skills; they never fade.',
            'Your career grows as you grow.',
            'Be valuable, not just available.',
            'Show your work; the world needs your talent.',
            'Opportunities favor the prepared.',
            'Ambition is the first step to success.',
            'Hard work beats luck.',
            "Build a career you're proud of.",
            'Learning is the path to mastery.',
            'Choose a job you love, and you will never have to work a day in your life. — Confucius',
            'The only way to do great work is to love what you do. — Steve Jobs',
            'Strive not to be a success, but rather to be of value. — Albert Einstein',
            'If you’re offered a seat on a rocket ship, don’t ask what seat. Just get on. — Sheryl Sandberg',
            'Do not wait to strike till the iron is hot; but make it hot by striking. — William Butler Yeats',
            'Skills pay the bills. — Unknown',
            'Be so good they can’t ignore you. — Steve Martin',
            'Work on your craft, not your ego. — Unknown',
            'Reputation is built in years and lost in seconds. — Unknown',
            'Your network is your net worth. — Unknown',
            'Success is where preparation and opportunity meet. — Bobby Unser',
            'Opportunities multiply as they are seized. — Sun Tzu',
            'Quality means doing it right when no one is looking. — Henry Ford',
            'Under-promise and over-deliver. — Unknown',
            'Keep learning. Stay valuable. — Unknown'],
 'Confidence': ['Confidence is built through action.',
                'Start small, build proof.',
                'Keep promises to yourself.',
                'Preparation breeds confidence.',
                'Be proud of progress.',
                'Your value is not up for debate.',
                'Learn, then lead.',
                'Confidence grows with reps.',
                'Stand tall in your truth.',
                'Focus on what you can do today.',
                'Courage creates confidence.',
                'Practice makes you powerful.',
                'Don’t wait for permission.',
                'Own your story.',
                'Celebrate small wins.',
                'Confidence is quiet consistency.',
                'Do it scared.',
                'Speak with clarity.',
                'Skills build self-belief.',
                'Keep improving.',
                'Let results talk.',
                'Stay curious, stay confident.',
                'Trust your work.',
                'Respect yourself.',
                'Your mindset matters.',
                'Show up again.',
                'Confidence is earned daily.'],
 'Courage': ['Courage is action with fear present.',
             'Bravery starts with one step.',
             'Discomfort is where growth lives.',
             'Speak the truth kindly.',
             'Start again—brave people do.',
             'Ask for help—also courage.',
             'Set boundaries with respect.',
             'Do hard things daily.',
             'Be yourself loudly and gently.',
             'Courage is choosing change.',
             'Failure is not fatal.',
             'Try before you’re ready.',
             'Take the shot.',
             'Be willing to be wrong.',
             'Risk is the price of progress.',
             'Face the thing you avoid.',
             'Courage is quiet sometimes.',
             'Keep going when it’s messy.',
             'Honor your values.',
             'Show up imperfectly.',
             'Take responsibility.',
             'Create despite criticism.',
             'Stand for what matters.',
             'Let fear ride, not drive.',
             'Start small, stay brave.',
             'Courage builds confidence.',
             'Do the next right thing.'],
 'Creativity': ['Creativity is intelligence having fun.',
                'Everything you can imagine is real.',
                'Ideas grow when shared.',
                'Creativity thrives in curiosity.',
                'Think differently; the world needs your ideas.',
                'Innovation begins with imagination.',
                'Let your mind wander—magic happens there.',
                'Create without fear.',
                "Mistakes are proof you're trying.",
                'Break the rules; make your own.',
                'Your voice is unique—use it.',
                'Art is freedom in motion.',
                'Imagination is more important than knowledge. — Albert Einstein',
                'Creativity takes courage. — Henri Matisse',
                'Art enables us to find ourselves and lose ourselves at the same time. — Thomas Merton',
                'You can’t use up creativity. The more you use, the more you have. — Maya Angelou',
                'The chief enemy of creativity is ‘good’ sense. — Pablo Picasso',
                'Create first, judge later. — Unknown',
                'Done is better than perfect. — Unknown',
                'Curiosity fuels creativity. — Unknown',
                'Make something today. — Unknown',
                'Start with what you have. — Unknown',
                'Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep. — Scott Adams',
                'Inspiration exists, but it has to find you working. — Pablo Picasso',
                'Everything you can imagine is real. — Pablo Picasso',
                'Creativity is a wild mind and a disciplined eye. — Dorothy Parker',
                'Art washes away from the soul the dust of everyday life. — Pablo Picasso'],
 'Discipline': ['Discipline is choosing what you want most over what you want now.',
                'Consistency creates results.',
                'Small steps every day lead to big changes.',
                'Discipline turns dreams into reality.',
                'Show up even when you don’t feel like it.',
                'Consistency beats intensity.',
                'Do it for your future self.',
                'Habits define your destiny.',
                'Stay focused; distractions can wait.',
                'Discipline is a superpower.',
                'You don’t get what you wish for; you get what you work for.',
                'Commitment is doing the work long after the mood has passed.',
                'Discipline is the bridge between goals and accomplishment. — Jim Rohn',
                'Freedom is born from discipline. — Jocko Willink',
                'We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle',
                'The future depends on what you do today. — Mahatma Gandhi',
                'Self-discipline is the magic power that makes you virtually unstoppable. — Dan Kennedy',
                'Discipline is self-love. — Unknown',
                'Do it daily. — Unknown',
                'Consistency is a superpower. — Unknown',
                'Discipline is the difference between goals and results. — Unknown',
                'Win the morning, win the day. — Unknown',
                'First you make habits, then habits make you. — Unknown',
                'Do what you said you would do. — Unknown',
                'Discipline creates freedom. — Unknown',
                'Stick to the plan. — Unknown',
                'Show up. That’s the job. — Unknown'],
 'Family': ['Family is your first team.',
            'Home is where you feel safe.',
            'Family is built with care.',
            'Small moments make big memories.',
            'Be present at home.',
            'Love is spelled T-I-M-E.',
            'Support creates strength.',
            'Listen more, assume less.',
            'Kindness keeps families close.',
            'Gratitude grows at home.',
            'Forgiveness heals.',
            'Protect the bond.',
            'Family is a daily choice.',
            'Show up for each other.',
            'Celebrate the ordinary.',
            'Respect builds trust.',
            'Home should feel like peace.',
            'Care is a language.',
            'Create traditions.',
            'Be the calm.',
            'Love lives in details.',
            'Help without being asked sometimes.',
            'Speak with warmth.',
            'Together is a superpower.',
            'Apologize quickly.',
            'Encourage often.',
            'Family is love in action.'],
 'Friendship': ['True friendship has no distance.',
                'Friends are the family we choose.',
                'Good friends make life better.',
                'A true friend brings out the best in you.',
                'Real friends are rare treasures.',
                'Friendship grows through kindness.',
                'Laughter is the bond of friendship.',
                'A friend understands without words.',
                'Friends make the world brighter.',
                'Support, love, and loyalty define friendship.',
                'Good friends lift you higher.',
                'Friendship is a gift to cherish.',
                'A friend is one of the nicest things you can have, and one of the best things you can be. — Douglas '
                'Pagels',
                'Friendship doubles joys and halves griefs. — Francis Bacon',
                'A real friend is one who walks in when the rest of the world walks out. — Walter Winchell',
                'The only way to have a friend is to be one. — Ralph Waldo Emerson',
                'True friendship comes when the silence between two people is comfortable. — David Tyson',
                'Good friends are good medicine. — Unknown',
                'Friendship is built on trust and time. — Unknown',
                'A friend makes the good times better and the hard times easier. — Unknown',
                'Friends are proof you’re not alone. — Unknown',
                'Real friends don’t compete; they connect. — Unknown',
                'Friendship is the comfort of knowing you’re understood. — Unknown',
                'Kindness is the language of friendship. — Unknown',
                'Be the friend you want. — Unknown',
                'True friends feel like home. — Unknown',
                'A little check-in goes a long way. — Unknown'],
 'Gratitude': ['Gratitude turns what we have into enough.',
               'A grateful heart attracts miracles.',
               'Appreciation unlocks abundance.',
               'Gratitude changes your state instantly.',
               'Count blessings, not problems.',
               'Thankfulness opens the door to joy.',
               'A grateful mindset transforms life.',
               'Gratitude is a magnet for positivity.',
               'See the good—it’s always there.',
               'The more you appreciate, the more you receive.',
               'Gratitude makes life richer.',
               'A grateful heart is a peaceful heart.',
               'Gratitude is not only the greatest of virtues, but the parent of all the others. — Cicero',
               'The more thankful I became, the more my bounty increased. — Oprah Winfrey',
               'Enjoy the little things, for one day you may look back and realize they were the big things. — Robert '
               'Brault',
               'Silent gratitude isn’t much use to anyone. — G. B. Stern',
               'Gratitude turns what we have into enough, and more. — Melody Beattie',
               'Gratitude is a shortcut to joy. — Unknown',
               'Gratitude changes everything. — Unknown',
               'Be thankful for small things. — Unknown',
               'Gratitude turns ordinary days into thanksgivings. — Unknown',
               'Appreciate what you have while working for what you want. — Unknown',
               'Gratitude is the healthiest of all human emotions. — Zig Ziglar',
               'Gratitude is riches. Complaint is poverty. — Doris Day',
               'Enjoy the now. Be grateful. — Unknown',
               'Gratitude makes room for more. — Unknown',
               'Say thank you more often. — Unknown'],
 'Leadership': ['Leadership is influence, not a title.',
                'Great leaders listen first.',
                'Clarity beats chaos.',
                'Trust is the currency of leadership.',
                'Lead by example.',
                'Own the outcome.',
                'Serve your team, then watch them grow.',
                'Consistency builds credibility.',
                'Decisions require courage.',
                'Vision gives direction.',
                'Leaders create leaders.',
                'Stay calm; your team mirrors you.',
                'Accountability is leadership.',
                'Kindness is strength.',
                'Communicate with purpose.',
                'Give credit, take responsibility.',
                'Leadership shows in hard moments.',
                'Ask better questions.',
                'Empower, don’t control.',
                'Be the standard.',
                'Discipline is contagious.',
                'Make the mission clear.',
                'Protect your people.',
                'Do the right thing, especially when hard.',
                'Earn respect daily.',
                'Lead with humility.',
                'A leader’s job is to make others better.'],
 'Learning': ['Curiosity is the engine of learning.',
              'Every mistake is data.',
              'Ask questions, grow faster.',
              'Practice makes knowledge stick.',
              'Learn, apply, repeat.',
              'Reading is a shortcut to wisdom.',
              'Skills compound like interest.',
              'Stay a beginner at heart.',
              'Small lessons daily add up.',
              'Feedback is fuel.',
              'Consistency beats cramming.',
              'Learn from people who’ve done it.',
              'Write it down to remember.',
              'Teach to understand.',
              'Learning expands options.',
              'Your future is built in study sessions.',
              'Progress loves patience.',
              'One new skill can change everything.',
              'Learn the basics deeply.',
              'Reflect to learn twice.',
              'Mindset shapes learning.',
              'Experience is a tough teacher.',
              'Study the process, not just results.',
              'Stay coachable.',
              'Learning never expires.',
              'Better inputs, better outputs.',
              'Grow your knowledge, grow your life.'],
 'Life': ['Life begins at the end of your comfort zone.',
          'Every moment is a fresh beginning.',
          'Happiness is found in the little things.',
          'Life is what you make it.',
          "Enjoy the present; it's all you truly have.",
          'Your thoughts shape your reality.',
          'Let go of what you can’t control.',
          'Choose joy every day.',
          'Life becomes easier when you stop comparing.',
          'What you focus on grows.',
          'Slow down; life is not a race.',
          'Be present, be grateful.',
          'Life is what happens while you are busy making other plans. — John Lennon',
          'Be the change that you wish to see in the world. — Mahatma Gandhi',
          'In the end, it’s not the years in your life that count. It’s the life in your years. — A. Lincoln',
          'Life rewards the brave. — Virgil',
          'The purpose of our lives is to be happy. — Dalai Lama',
          'This too shall pass. — Persian proverb',
          'Life is a collection of moments; make them count. — Unknown',
          'Wherever you go, go with all your heart. — Confucius',
          'Life is really simple, but we insist on making it complicated. — Confucius',
          'Be where your feet are. — Unknown',
          'Life is 10% what happens to you and 90% how you react. — Charles R. Swindoll',
          'Let your life be your message. — Mahatma Gandhi',
          'Live less out of habit and more out of intent. — Unknown',
          'Choose kindness; it always fits. — Unknown',
          'Everything has beauty, but not everyone sees it. — Confucius'],
 'Love': ['Love grows where kindness lives.',
          'Love is a daily choice.',
          'Small gestures keep love alive.',
          'Love is trust in motion.',
          'Love is built, not found.',
          'Love listens before it speaks.',
          'Love is patience with a warm heart.',
          'Love is seeing the good first.',
          'Love is teamwork, not tug-of-war.',
          'Love is honesty with tenderness.',
          'Love is giving without keeping score.',
          'Love is safety in someone’s presence.',
          'Love is a quiet strength.',
          'Love is respect in action.',
          'Love is being present.',
          'Love is gentle courage.',
          'Love is laughter shared.',
          'Love is learning each other again.',
          'Love is consistency.',
          'Love is taking responsibility.',
          'Love is choosing peace together.',
          'Love is empathy made visible.',
          'Love is attention.',
          'Love is growth together.',
          'Love is a home you build.',
          'Love is the art of care.',
          'Love makes life meaningful.'],
 'Mindset': ['Your mind sets your direction.',
             'Focus grows what matters.',
             'Thoughts become habits.',
             'Habits become outcomes.',
             'Control the controllables.',
             'Be kind to your inner voice.',
             'Comparison steals peace.',
             'Choose progress over perfection.',
             'Small wins build momentum.',
             'Calm mind, clear path.',
             'Confidence follows action.',
             'Fear is often imagined.',
             'Stay solution-focused.',
             'Energy follows attention.',
             'Discomfort is a teacher.',
             'Resilience is a mindset.',
             'Treat setbacks as feedback.',
             'Your story is still being written.',
             'Start before you feel ready.',
             'Consistency creates identity.',
             'Protect your mental space.',
             'Your attitude is a daily decision.',
             'Hope is a strategy.',
             'Keep your standards high.',
             'Talk to yourself like a friend.',
             'Presence is power.',
             'Train your mind like a muscle.'],
 'Money & Finance': ['Money is a tool, not a trophy.',
                     'Budgeting is freedom planning.',
                     'Spend intentionally.',
                     'Small savings add up.',
                     'Protect your downside.',
                     'Invest in knowledge first.',
                     'Debt is future effort borrowed.',
                     'Cash flow matters.',
                     'Diversification reduces risk.',
                     'Pay yourself first.',
                     'Track it, then improve it.',
                     'Needs before wants.',
                     'Good finances are good habits.',
                     'Time beats timing.',
                     'Compound growth rewards patience.',
                     'Build an emergency fund.',
                     'Your plan is your power.',
                     'Grow income, control expenses.',
                     'Value creation drives income.',
                     'Don’t trade long-term for short-term.',
                     'Risk without research is gambling.',
                     'Simple beats complicated.',
                     'Financial peace is a process.',
                     'Money follows discipline.',
                     'Delay gratification, build wealth.',
                     'Protect your time and money.',
                     'Make your money serve your life.'],
 'Motivation': ['Difficult roads often lead to beautiful destinations.',
                'Start where you are, use what you have, do what you can.',
                "Keep going, you're getting stronger.",
                'Small steps today create big results tomorrow.',
                "Believe you can and you're halfway there.",
                'Growth begins at the end of your comfort zone.',
                'Your only limit is your mind.',
                'Push yourself; no one will do it for you.',
                'Great things take time—stay patient.',
                'You become what you repeatedly do.',
                "Stay committed, even when it's hard.",
                'Today is a perfect day to try.',
                'The only limit to our realization of tomorrow is our doubts of today. — F. D. Roosevelt',
                'Act as if what you do makes a difference. It does. — William James',
                'It always seems impossible until it’s done. — Nelson Mandela',
                'Whether you think you can or you think you can’t, you’re right. — Henry Ford',
                'You miss 100% of the shots you don’t take. — Wayne Gretzky',
                'One step can change everything. — Unknown',
                'Don’t wait for motivation; build momentum. — Unknown',
                'Progress, not perfection. — Unknown',
                'Your future self is watching. — Unknown',
                'Do it scared. — Unknown',
                'A journey of a thousand miles begins with a single step. — Lao Tzu',
                'Believe you deserve it and the universe will serve it. — Unknown',
                'Make it happen. Shock everyone. — Unknown',
                'If it matters to you, you’ll find a way. — Unknown',
                'Start now. Start messy. — Unknown'],
 'Patience': ['Patience is strength in slow motion.',
              'Good things take time.',
              'Trust the process.',
              'Seeds don’t grow overnight.',
              'Stay steady.',
              'Patience protects peace.',
              'Wait with purpose.',
              'Progress is not instant.',
              'Consistency requires patience.',
              'Patience is disciplined hope.',
              'Breathe and continue.',
              'Patience is emotional control.',
              'Long games create big wins.',
              'Don’t rush what matters.',
              'Time reveals results.',
              'Stay calm, stay committed.',
              'Patience is practiced daily.',
              'Slow is smooth, smooth is fast.',
              'Let it unfold.',
              'Patience is quiet confidence.',
              'Keep building.',
              'Small steps need time.',
              'Hold the vision.',
              'Your time will come.',
              'Patience reduces regret.',
              'Be gentle with yourself.',
              'Endurance is patience in action.'],
 'Resilience': ['Fall seven times, stand up eight.',
                'Storms make trees take deeper roots.',
                'Hard times create strong people.',
                'Pain is temporary, strength is forever.',
                'The struggle you’re in today builds your tomorrow.',
                'Not all storms come to disrupt; some come to clear your path.',
                'Keep fighting; better days are ahead.',
                'You are stronger than you think.',
                'Rise after every fall.',
                'Every setback is a setup for a comeback.',
                'Your resilience defines your journey.',
                'Hold on; your breakthrough is coming.',
                'That which does not kill us makes us stronger. — Friedrich Nietzsche',
                'Tough times never last, but tough people do. — Robert Schuller',
                'The human capacity for burden is like bamboo—far more flexible than you’d ever believe. — Jodi '
                'Picoult',
                'When you have exhausted all possibilities, remember this: you haven’t. — Thomas Edison',
                'Our greatest glory is not in never falling, but in rising every time we fall. — Confucius',
                'Keep going. You’re closer than you think. — Unknown',
                'Adapt. Adjust. Overcome. — Unknown',
                'Your comeback will be stronger than your setback. — Unknown',
                'Pressure builds diamonds. — Unknown',
                'Hard days build strong minds. — Unknown',
                'Strength grows in the moments you think you can’t go on but keep going. — Unknown',
                'Turn wounds into wisdom. — Oprah Winfrey',
                'Rock bottom became the solid foundation on which I rebuilt my life. — J. K. Rowling',
                'Don’t count the days; make the days count. — Muhammad Ali',
                'Fall down seven times, stand up eight. — Japanese proverb'],
 'Self-care': ['Take care of yourself first.',
               'Self-care is how you take your power back.',
               'Rest is part of the process.',
               'You deserve the same love you give others.',
               'Pausing is not quitting.',
               'Your well-being matters.',
               'Protect your energy.',
               'Healing takes time—be gentle with yourself.',
               "Breathe; you're doing your best.",
               'Prioritize your peace.',
               'Self-care is a daily practice.',
               "It's okay to take a break.",
               'To love oneself is the beginning of a lifelong romance. — Oscar Wilde',
               'The greatest wealth is health. — Virgil',
               'Almost everything will work again if you unplug it for a few minutes, including you. — Anne Lamott',
               'Your calm mind is the ultimate weapon against your challenges. — Bryant McGill',
               'Caring for myself is not self-indulgence, it is self-preservation. — Audre Lorde',
               'Self-care is a strategy, not a luxury. — Unknown',
               'Protect your peace. — Unknown',
               'Slow down to speed up. — Unknown',
               'Rest is productive. — Unknown',
               'Boundaries are self-respect in action. — Unknown',
               'You can’t pour from an empty cup. — Unknown',
               'Give yourself the same grace you give others. — Unknown',
               'Take a deep breath. You’re allowed to pause. — Unknown',
               'Your body hears everything your mind says. — Naomi Judd',
               'Make your mental health a priority. — Unknown'],
 'Sport': ['I float like a butterfly, sting like a bee. — Muhammad Ali',
           'Champions keep playing until they get it right.',
           'Winners train, losers complain.',
           'Every rep counts.',
           "Your body can stand almost anything; it's your mind you must convince.",
           'Train hard, stay humble.',
           'The pain you feel today is the strength you gain tomorrow.',
           'Strong mind, strong body.',
           'Don’t limit your challenges; challenge your limits.',
           'Sweat is your body crying for progress.',
           'Discipline beats motivation.',
           'One more rep can change everything.',
           'I can accept failure, everyone fails at something. But I can’t accept not trying. — Michael Jordan',
           'Everything negative can be turned into motivation to succeed. — Kobe Bryant',
           'Success is a journey, not a destination. — Serena Williams',
           'If you are afraid of failure, you don’t deserve to be successful. — Charles Barkley',
           'Only the disciplined are free. — Eliud Kipchoge',
           'Train like it’s a privilege. — Unknown',
           'Earn your confidence. — Unknown',
           'Strong mind. Strong body. — Unknown',
           'Every day is a chance to get better. — Unknown',
           'Champions are made in the off-season. — Unknown',
           'The pain you feel today will be the strength you feel tomorrow. — Unknown',
           'It never gets easier; you just get better. — Greg LeMond',
           'Run the day. Don’t let it run you. — Unknown',
           'Suffer now and live the rest of your life as a champion. — Muhammad Ali',
           'Fall in love with the process. — Unknown'],
 'Success': ['Success is not final; failure is not fatal.',
             'Success is the sum of small efforts repeated daily.',
             'Dream big. Work hard. Stay focused.',
             'Success starts with self-belief.',
             'Winners are not people who never fail but people who never quit.',
             'Great achievements require dedication.',
             'Preparation turns opportunities into success.',
             'Your habits shape your success.',
             'Do what others won’t, achieve what others can’t.',
             'Every accomplishment begins with the decision to try.',
             'Stay hungry, stay humble.',
             'The harder you work, the greater the reward.',
             'Opportunities don’t happen. You create them. — Chris Grosser',
             'Success usually comes to those who are too busy to be looking for it. — H. D. Thoreau',
             'The way to get started is to quit talking and begin doing. — Walt Disney',
             'Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill',
             'If you can dream it, you can do it. — Walt Disney',
             'Success is rented, and rent is due every day. — Unknown',
             'Consistency beats talent when talent isn’t consistent. — Unknown',
             'Small wins add up. — Unknown',
             'Success is built on habits, not hype. — Unknown',
             'Focus on systems, not just goals. — Unknown',
             'Failure is simply the opportunity to begin again. — Henry Ford',
             'Success is the progressive realization of a worthy goal. — Earl Nightingale',
             'Luck is what happens when preparation meets opportunity. — Seneca',
             'Discipline is the foundation of success. — Unknown',
             'Dreams don’t work unless you do. — John C. Maxwell'],
 'Wisdom': ['Wisdom is knowing what matters.',
            'Less noise, more insight.',
            'Wisdom listens.',
            'Wisdom asks better questions.',
            'Wisdom is calm under pressure.',
            'Experience is a teacher; reflection is the lesson.',
            'Wisdom is simple, not easy.',
            'Wisdom chooses long-term.',
            'Wisdom is humility.',
            'Wisdom is learning from others.',
            'Wisdom is restraint.',
            'Wisdom is kindness with boundaries.',
            'Wisdom is clarity.',
            'Wisdom is perspective.',
            'Wisdom is knowing when to stop.',
            'Wisdom is patience.',
            'Wisdom is gratitude.',
            'Wisdom is self-awareness.',
            'Wisdom is consistency.',
            'Wisdom is compassion.',
            'Wisdom is quiet confidence.',
            'Wisdom is intentional living.',
            'Wisdom avoids extremes.',
            'Wisdom is honesty.',
            'Wisdom is choosing peace.',
            'Wisdom is being teachable.',
            'Wisdom turns knowledge into action.']}

SPECIAL_DAYS = {'EN': {'01-01': {'quotes': ['New year, new beginnings.',
                             'Today is a great day to start again.',
                             'Set the intention, take the step.',
                             'First rule of the year: keep going.'],
                  'title': 'New Year'},
        '02-14': {'quotes': ['Love is built in the small moments.',
                             'Choose kindness, choose love.',
                             'Love is attention and effort.',
                             'A gentle heart is a strong heart.'],
                  'title': 'Valentine’s Day'},
        '03-08': {'quotes': ['Courage and kindness change the world.',
                             'Celebrate strength, talent, and effort.',
                             'Equality is progress for everyone.',
                             'When women rise, the world rises.'],
                  'title': 'International Women’s Day'},
        '04-23': {'quotes': ['Children’s joy is tomorrow’s light.',
                             'Hope grows where curiosity lives.',
                             'The future is shaped by today’s learners.',
                             'Protect wonder, grow the future.'],
                  'title': 'Children’s Day'},
        '05-01': {'quotes': ['Work gives value meaning.',
                             'Build together, grow together.',
                             'Solidarity is strength.',
                             'Respect work, respect people.'],
                  'title': 'Labor Day'},
        '05-19': {'quotes': ['Every new beginning starts with courage.',
                             'Youth is the energy of tomorrow.',
                             'Commit to the path you believe in.',
                             'Move forward with purpose.'],
                  'title': 'Commemoration of Atatürk, Youth and Sports Day'},
        '10-29': {'quotes': ['Freedom is a shared future.',
                             'Values build nations.',
                             'Hope is the strongest legacy.',
                             'Unity is power.'],
                  'title': 'Republic Day'},
        '11-10': {'quotes': ['To remember is to keep values alive.',
                             'Vision lights the future.',
                             'Respect is where learning begins.',
                             'Work for a better tomorrow.'],
                  'title': 'Day of Remembrance'},
        '12-31': {'quotes': ['Not an ending—just a summary of lessons.',
                             'Let go of what you learned; keep the growth.',
                             'Reflect, reset, restart.',
                             'Grateful for today, ready for tomorrow.'],
                  'title': 'Year End'}},
 'TR': {'01-01': {'quotes': ['Yeni yıl, yeni başlangıçlar demektir.',
                             'Bugün yeni bir sayfa açmak için mükemmel bir gün.',
                             'Niyetini netleştir, adımını at.',
                             'Yeni yılın ilk sözü: devam.'],
                  'title': 'Yeni Yıl'},
        '02-14': {'quotes': ['Sevgi, en güçlü motivasyondur.',
                             'Aşk, günlük bir özen işidir.',
                             'Sevgi, küçük şeylerde saklıdır.',
                             'Kalpten gelen, kalbe gider.'],
                  'title': 'Sevgililer Günü'},
        '03-08': {'quotes': ['Güç, şefkatle birleşince dönüşüm başlar.',
                             'Emeği ve cesareti kutla.',
                             'Eşitlik, daha iyi bir gelecek demektir.',
                             'İlham veren kadınlar, dünyayı değiştirir.'],
                  'title': 'Dünya Kadınlar Günü'},
        '04-23': {'quotes': ['Çocukların gülüşü, geleceğin ışığıdır.',
                             'Umut, en çok çocuklarda büyür.',
                             'Yarın, bugün yetişenlerle şekillenir.',
                             'Gelecek; merak edenlerin ve öğrenenlerin.'],
                  'title': '23 Nisan'},
        '05-01': {'quotes': ['Emek, değerin en temiz hâlidir.',
                             'Birlikte üretmek, birlikte büyümektir.',
                             'Dayanışma, zor günlerin köprüsüdür.',
                             'Emeğe saygı, insana saygıdır.'],
                  'title': 'Emek ve Dayanışma Günü'},
        '05-19': {'quotes': ['Bir başlangıç, bir milletin kaderini değiştirir.',
                             'Gençlik, geleceğin enerjisidir.',
                             'Cesaret, tarihe yön verir.',
                             'İnandığın yolda kararlılıkla yürü.'],
                  'title': '19 Mayıs'},
        '10-29': {'quotes': ['Özgürlük, birlikte kurulan bir gelecektir.',
                             'Cumhuriyet, ortak değerlerdir.',
                             'Umut, en güçlü mirastır.',
                             'Birlik, en büyük güçtür.'],
                  'title': 'Cumhuriyet Bayramı'},
        '11-10': {'quotes': ['Hatırlamak, değerleri yaşatmanın yoludur.',
                             'İlke ve vizyon, geleceği aydınlatır.',
                             'Saygı, öğrenmenin başlangıcıdır.',
                             'Daha iyi bir yarın için çalış.'],
                  'title': '10 Kasım'},
        '12-31': {'quotes': ['Bugün kapanış değil, derslerin özeti.',
                             'Geçen yılın yükünü bırak, yeniyi karşıla.',
                             'Şükret, değerlendir, hedefle.',
                             'Yarın için niyet et, bugün için teşekkür et.'],
                  'title': 'Yılın Son Günü'}}}


def get_daily_quote(lang: str = "TR", date: Optional[datetime.date] = None) -> Dict[str, Any]:
    """Return a daily quote.
    - If the date matches a SPECIAL_DAYS entry, returns a themed quote.
    - Otherwise returns a random quote from all categories.
    lang: "TR" or "EN"
    """
    if date is None:
        date = datetime.date.today()

    lang = (lang or "TR").upper()
    quotes_db = QUOTES_TR if lang == "TR" else QUOTES_EN
    special_db = SPECIAL_DAYS.get("TR" if lang == "TR" else "EN", {})

    key = f"{date.month:02d}-{date.day:02d}"
    if key in special_db:
        info = special_db[key]
        q = random.choice(info["quotes"])
        return {
            "quote": q,
            "category": "Special Day",
            "is_special": True,
            "special_title": info.get("title"),
            "date_key": key,
        }

    # Normal random quote
    category = random.choice(list(quotes_db.keys()))
    q = random.choice(quotes_db[category])
    return {
        "quote": q,
        "category": category,
        "is_special": False,
        "special_title": None,
        "date_key": key,
    }
